<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BookingRatingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('booking_ratings')->delete();
        
        \DB::table('booking_ratings')->insert(array (
            0 => 
            array (
                'id' => 1,
                'booking_id' => 35,
                'service_id' => 11,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Efficient and precise Split AC installation, 5 stars! 🥰⚒️',
                'deleted_at' => NULL,
                'created_at' => '2023-09-12 06:40:06',
                'updated_at' => '2023-09-12 06:40:06',
            ),
            1 => 
            array (
                'id' => 2,
                'booking_id' => 35,
                'service_id' => 11,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Efficient and precise Split AC installation, 5 stars! 🥰⚒️',
                'deleted_at' => '2023-09-12 06:40:47',
                'created_at' => '2023-09-12 06:40:06',
                'updated_at' => '2023-09-12 06:40:47',
            ),
            2 => 
            array (
                'id' => 3,
                'booking_id' => 105,
                'service_id' => 70,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Incredible selection and quality in contemporary style clothing! My new go-to for fashion-forward pieces. A solid 5-star experience. 👏🏻',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 09:45:51',
                'updated_at' => '2023-09-29 09:45:51',
            ),
            3 => 
            array (
                'id' => 4,
                'booking_id' => 104,
                'service_id' => 98,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Flawless security camera setup - quick, professional, and hassle-free. 😎',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 09:49:37',
                'updated_at' => '2023-09-29 09:49:37',
            ),
            4 => 
            array (
                'id' => 5,
                'booking_id' => 103,
                'service_id' => 68,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Reliable and vigilant residential security patrol service, providing peace of mind 24/7.🤩',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 09:53:40',
                'updated_at' => '2023-09-29 09:53:40',
            ),
            5 => 
            array (
                'id' => 6,
                'booking_id' => 102,
                'service_id' => 95,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Impeccable car interior sanitization! My vehicle feels fresh and clean. 🚗🚐',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 09:56:33',
                'updated_at' => '2023-09-29 09:57:07',
            ),
            6 => 
            array (
                'id' => 7,
                'booking_id' => 101,
                'service_id' => 96,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The manicure and pedicure service was top-notch, leaving my nails looking flawless. 💅🏻',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 09:59:59',
                'updated_at' => '2023-09-29 10:00:44',
            ),
            7 => 
            array (
                'id' => 8,
                'booking_id' => 100,
                'service_id' => 108,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Excellent fixture installation plumbing service! Prompt, efficient, and flawless work. 🛠️',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 10:05:35',
                'updated_at' => '2023-09-29 10:05:35',
            ),
            8 => 
            array (
                'id' => 9,
                'booking_id' => 99,
                'service_id' => 73,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Exquisite wedding photography! Every moment beautifully captured. A heartfelt 5-star rating.🖼️📸',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 10:10:28',
                'updated_at' => '2023-09-29 10:10:28',
            ),
            9 => 
            array (
                'id' => 10,
                'booking_id' => 98,
                'service_id' => 65,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Exceptional rodent trapping service! Swift and effective, they resolved our pest problem. 😎',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 10:17:28',
                'updated_at' => '2023-09-29 10:17:28',
            ),
            10 => 
            array (
                'id' => 11,
                'booking_id' => 97,
                'service_id' => 62,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Exceptional career and finance consultation! Insightful advice that\'s making a positive impact. 😇',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 10:23:36',
                'updated_at' => '2023-09-29 10:24:32',
            ),
            11 => 
            array (
                'id' => 12,
                'booking_id' => 96,
                'service_id' => 91,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Exceptional custom stenciling service! Precision and creativity combined to perfection. 😎',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 10:26:25',
                'updated_at' => '2023-09-29 10:26:25',
            ),
            12 => 
            array (
                'id' => 13,
                'booking_id' => 95,
                'service_id' => 80,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Exceptional care for my evening gowns and formal attire! Impeccable cleaning and attention to detail. 😍😎',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 11:05:20',
                'updated_at' => '2023-09-29 11:05:20',
            ),
            13 => 
            array (
                'id' => 14,
                'booking_id' => 94,
                'service_id' => 49,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Exceptional lawn mowing and trimming! 🌾 Our yard looks immaculate, and the service was prompt and professional.🌲',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 11:37:19',
                'updated_at' => '2023-09-29 11:38:35',
            ),
            14 => 
            array (
                'id' => 15,
                'booking_id' => 93,
                'service_id' => 99,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Exceptional circuit repair service! Swift response and expert resolution. 🪛🔩🛠️',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 11:39:46',
                'updated_at' => '2023-09-29 11:39:46',
            ),
            15 => 
            array (
                'id' => 16,
                'booking_id' => 92,
                'service_id' => 46,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Exceptional dessert chef! 🥞🥯🍰🍮 Their creations were a delectable masterpiece, and the service was impeccable. ❤️',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 11:42:28',
                'updated_at' => '2023-09-29 11:43:21',
            ),
            16 => 
            array (
                'id' => 17,
                'booking_id' => 91,
                'service_id' => 35,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Exceptional kitchen and bathroom deep cleaning! 🧹🧽 They transformed our spaces into spotless havens. 🧼🪣',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 11:50:12',
                'updated_at' => '2023-09-29 11:50:12',
            ),
            17 => 
            array (
                'id' => 18,
                'booking_id' => 90,
                'service_id' => 17,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Exceptional beam and column installation! The precision and expertise of the team were outstanding. 😊🛠️',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 11:51:20',
                'updated_at' => '2023-09-29 11:51:20',
            ),
            18 => 
            array (
                'id' => 19,
                'booking_id' => 89,
                'service_id' => 33,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Exceptional transmission repair service! 🛠️🪛 They fixed our car swiftly and professionally. 😍🤩',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 11:52:28',
                'updated_at' => '2023-09-29 11:52:43',
            ),
            19 => 
            array (
                'id' => 20,
                'booking_id' => 88,
                'service_id' => 97,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Exceptional compressor fix service! 🪛🛠️ Swift and effective repair, our appliances are running perfectly. 😍😎',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 11:53:43',
                'updated_at' => '2023-09-29 11:54:31',
            ),
            20 => 
            array (
                'id' => 21,
                'booking_id' => 87,
                'service_id' => 110,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Exceptional filter replacement service! 🔧🪛  Prompt and professional, our air is now pure and clean.☺️',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 11:55:44',
                'updated_at' => '2023-09-29 11:55:44',
            ),
            21 => 
            array (
                'id' => 22,
                'booking_id' => 86,
                'service_id' => 38,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Good paint protection and polishing service! 🖌️ My vehicle looks showroom-ready. A solid 5-star rating! 🥰',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 12:03:04',
                'updated_at' => '2023-09-29 12:03:04',
            ),
            22 => 
            array (
                'id' => 23,
                'booking_id' => 85,
                'service_id' => 34,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Exceptional door casing and trim service! Precision and attention to detail were remarkable. 🛠️🪛',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 12:04:02',
                'updated_at' => '2023-09-29 12:04:02',
            ),
            23 => 
            array (
                'id' => 24,
                'booking_id' => 84,
                'service_id' => 107,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Our workspace has never been so pristine. A solid 5-star rating!🧽🧹🧼🪣',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 12:05:00',
                'updated_at' => '2023-09-29 12:05:08',
            ),
            24 => 
            array (
                'id' => 25,
                'booking_id' => 80,
                'service_id' => 105,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Exceptional custom cake creations! 🍰🍮 The chef\'s artistry and flavors were pure perfection. A well-deserved 5-star rating! 😍',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 12:06:10',
                'updated_at' => '2023-09-29 12:06:23',
            ),
            25 => 
            array (
                'id' => 26,
                'booking_id' => 79,
                'service_id' => 106,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The work was done flawlessly, and our home is now safe and efficient. 🔧⚙️🔩',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 12:21:33',
                'updated_at' => '2023-09-29 12:21:33',
            ),
            26 => 
            array (
                'id' => 27,
                'booking_id' => 78,
                'service_id' => 86,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Impressed by the thoroughness and expertise in pruning and trimming. Our landscape looks fantastic! 🌾',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 12:24:40',
                'updated_at' => '2023-09-29 12:24:40',
            ),
            27 => 
            array (
                'id' => 28,
                'booking_id' => 77,
                'service_id' => 92,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Impressive leather and suede cleaning service! 🧥🥼My items look brand new, and the quality of work is remarkable. Highly recommended! 😍',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 12:27:13',
                'updated_at' => '2023-09-29 12:27:23',
            ),
            28 => 
            array (
                'id' => 29,
                'booking_id' => 75,
                'service_id' => 100,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Incredible artistic frame design! They transformed our artwork into a masterpiece. 🖌️🖼️',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 12:28:35',
                'updated_at' => '2023-09-29 12:28:35',
            ),
            29 => 
            array (
                'id' => 30,
                'booking_id' => 74,
                'service_id' => 84,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Insightful relationship compatibility reading! It provided valuable clarity and guidance. Highly satisfied with the service.😍',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 12:30:13',
                'updated_at' => '2023-09-29 12:30:13',
            ),
            30 => 
            array (
                'id' => 31,
                'booking_id' => 73,
                'service_id' => 83,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'You solved our pest problem efficiently, making our home pest-free. Highly satisfied with their service. 😊',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 12:31:13',
                'updated_at' => '2023-09-29 12:32:23',
            ),
            31 => 
            array (
                'id' => 32,
                'booking_id' => 72,
                'service_id' => 82,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The quality of work and coverage by the corporate event photographer were truly remarkable. 📸❤️',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 12:32:54',
                'updated_at' => '2023-09-29 12:32:54',
            ),
            32 => 
            array (
                'id' => 33,
                'booking_id' => 71,
                'service_id' => 108,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Outstanding plumbing service for fixture installation! 🔩⚙️The technician was highly skilled, and everything works perfectly. ❤️',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 12:35:10',
                'updated_at' => '2023-09-29 12:35:10',
            ),
            33 => 
            array (
                'id' => 34,
                'booking_id' => 70,
                'service_id' => 102,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The exfoliation and peel service left my skin refreshed and radiant. 🧖',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 12:57:22',
                'updated_at' => '2023-09-29 12:57:22',
            ),
            34 => 
            array (
                'id' => 35,
                'booking_id' => 69,
                'service_id' => 109,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Thorough home sanitization service, providing peace of mind. 😍',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 13:05:57',
                'updated_at' => '2023-09-29 13:05:57',
            ),
            35 => 
            array (
                'id' => 36,
                'booking_id' => 68,
                'service_id' => 90,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The commercial building security service provided a sense of safety and trust. 👮🏻',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 13:07:12',
                'updated_at' => '2023-09-29 13:07:12',
            ),
            36 => 
            array (
                'id' => 37,
                'booking_id' => 67,
                'service_id' => 103,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Efficient smart TV integration that simplified our entertainment setup. 🤩🪛🔩',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 13:08:29',
                'updated_at' => '2023-09-29 13:08:29',
            ),
            37 => 
            array (
                'id' => 38,
                'booking_id' => 66,
                'service_id' => 104,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The seam repair and reinforcement service provided solid and lasting results. 🪡🧵🧶',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 13:09:57',
                'updated_at' => '2023-09-29 13:09:57',
            ),
            38 => 
            array (
                'id' => 39,
                'booking_id' => 106,
                'service_id' => 101,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Timely and effective leak repair service, a lifesaver for our home. 🪛🛠️🔩',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 13:17:56',
                'updated_at' => '2023-09-29 13:17:56',
            ),
            39 => 
            array (
                'id' => 40,
                'booking_id' => 108,
                'service_id' => 59,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The bespoke suits and dresses service tailored our attire to perfection, reflecting our style. 👘🥻',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 14:10:39',
                'updated_at' => '2023-09-29 14:11:20',
            ),
            40 => 
            array (
                'id' => 41,
                'booking_id' => 109,
                'service_id' => 71,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The alarm system installation was executed with precision, enhancing our security. 🤩',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 14:12:18',
                'updated_at' => '2023-09-29 14:12:18',
            ),
            41 => 
            array (
                'id' => 42,
                'booking_id' => 110,
                'service_id' => 55,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The VIP escort protection service ensured our safety discreetly and professionally. 👮🏻‍♀️👮🏻',
                'deleted_at' => NULL,
                'created_at' => '2023-09-29 14:13:07',
                'updated_at' => '2023-10-02 13:08:07',
            ),
            42 => 
            array (
                'id' => 43,
                'booking_id' => 127,
                'service_id' => 37,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The AC coolant renewal service improved our cooling system\'s efficiency effectively. 🤩',
                'deleted_at' => NULL,
                'created_at' => '2023-09-30 07:46:12',
                'updated_at' => '2023-09-30 07:46:12',
            ),
            43 => 
            array (
                'id' => 44,
                'booking_id' => 126,
                'service_id' => 93,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The airflow AC problem identification service efficiently pinpointed and fixed our cooling issue. ❤️',
                'deleted_at' => NULL,
                'created_at' => '2023-09-30 07:47:35',
                'updated_at' => '2023-09-30 07:47:35',
            ),
            44 => 
            array (
                'id' => 45,
                'booking_id' => 124,
                'service_id' => 32,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The interior car cleaning service left my car looking refreshed and clean, a job well done. 🏎️🚙🚗',
                'deleted_at' => NULL,
                'created_at' => '2023-09-30 07:48:33',
                'updated_at' => '2023-09-30 07:48:47',
            ),
            45 => 
            array (
                'id' => 46,
                'booking_id' => 123,
                'service_id' => 16,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The cabinet fix 🪚 and refinish service 🛠️ breathed new life into our cabinets with skill and precision.',
                'deleted_at' => NULL,
                'created_at' => '2023-09-30 07:50:26',
                'updated_at' => '2023-09-30 07:51:53',
            ),
            46 => 
            array (
                'id' => 47,
                'booking_id' => 122,
                'service_id' => 22,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The chimney sweeping service thoroughly cleaned and ensured our home\'s safety. 🧹🧽🧼',
                'deleted_at' => NULL,
                'created_at' => '2023-09-30 07:58:20',
                'updated_at' => '2023-09-30 07:58:20',
            ),
            47 => 
            array (
                'id' => 48,
                'booking_id' => 121,
                'service_id' => 27,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The Italian cook service delivered a mouthwatering experience, with every dish bursting with authentic flavors. 🥘🍕🍝',
                'deleted_at' => NULL,
                'created_at' => '2023-09-30 07:59:59',
                'updated_at' => '2023-09-30 07:59:59',
            ),
            48 => 
            array (
                'id' => 49,
                'booking_id' => 120,
                'service_id' => 85,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The fault diagnosis service provided invaluable insights, resolving issues with precision.  🛠️🪛',
                'deleted_at' => NULL,
                'created_at' => '2023-09-30 08:02:15',
                'updated_at' => '2023-09-30 08:02:15',
            ),
            49 => 
            array (
                'id' => 50,
                'booking_id' => 119,
                'service_id' => 47,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The Green Space Guardians service truly nurtured our garden, turning it into a flourishing oasis. 🌾🌿',
                'deleted_at' => NULL,
                'created_at' => '2023-09-30 09:29:51',
                'updated_at' => '2023-09-30 09:30:22',
            ),
            50 => 
            array (
                'id' => 51,
                'booking_id' => 118,
                'service_id' => 76,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The silk and designer garment care service treated our wardrobe with utmost care and attention. 😍👘🥻',
                'deleted_at' => NULL,
                'created_at' => '2023-09-30 09:31:20',
                'updated_at' => '2023-09-30 09:31:20',
            ),
            51 => 
            array (
                'id' => 52,
                'booking_id' => 117,
                'service_id' => 81,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The multi-frame set painting service beautifully adorned our space with creativity. 🏞️🖼️',
                'deleted_at' => NULL,
                'created_at' => '2023-09-30 09:32:37',
                'updated_at' => '2023-09-30 09:32:37',
            ),
            52 => 
            array (
                'id' => 53,
                'booking_id' => 116,
                'service_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The marriage puja service added a sacred and harmonious touch to our special day. 🪔🔥',
                'deleted_at' => NULL,
                'created_at' => '2023-09-30 09:35:45',
                'updated_at' => '2023-09-30 09:35:45',
            ),
            53 => 
            array (
                'id' => 54,
                'booking_id' => 115,
                'service_id' => 63,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Efficient bed bug eradication service that restored our peace at home. 🥰',
                'deleted_at' => NULL,
                'created_at' => '2023-09-30 09:39:20',
                'updated_at' => '2023-09-30 09:39:20',
            ),
            54 => 
            array (
                'id' => 55,
                'booking_id' => 114,
                'service_id' => 44,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Captured beautiful moments with our family and loved ones. 🖼️📸',
                'deleted_at' => NULL,
                'created_at' => '2023-09-30 09:40:32',
                'updated_at' => '2023-09-30 09:40:32',
            ),
            55 => 
            array (
                'id' => 56,
                'booking_id' => 113,
                'service_id' => 87,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Efficient sewer line cleaning service, they swiftly resolved the issue. 🔥🥰',
                'deleted_at' => NULL,
                'created_at' => '2023-09-30 09:41:35',
                'updated_at' => '2023-09-30 09:41:35',
            ),
            56 => 
            array (
                'id' => 57,
                'booking_id' => 112,
                'service_id' => 94,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The haircut and styling service left me feeling confident and refreshed. 💇🏻😍🥰',
                'deleted_at' => NULL,
                'created_at' => '2023-09-30 09:48:28',
                'updated_at' => '2023-09-30 09:48:28',
            ),
            57 => 
            array (
                'id' => 58,
                'booking_id' => 111,
                'service_id' => 89,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Thorough outdoor area sanitization – a vital service in today\'s climate. 🔥👏🏻',
                'deleted_at' => NULL,
                'created_at' => '2023-09-30 09:50:10',
                'updated_at' => '2023-09-30 09:50:10',
            ),
            58 => 
            array (
                'id' => 59,
                'booking_id' => 143,
                'service_id' => 57,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The tailor\'s hemming and length adjustment service 🥻👗 was skillfully executed, enhancing the fit of our clothing. 👚👕👖',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 06:30:36',
                'updated_at' => '2023-10-02 07:07:11',
            ),
            59 => 
            array (
                'id' => 60,
                'booking_id' => 142,
                'service_id' => 69,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The smart lock installation  🔐service upgraded our security with precision. 😍',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 06:32:51',
                'updated_at' => '2023-10-02 06:32:51',
            ),
            60 => 
            array (
                'id' => 61,
                'booking_id' => 141,
                'service_id' => 52,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The bodyguard service 👮🏻‍♀️ ensured our safety with utmost professionalism and diligence. 👮🏻‍♀️',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 06:34:02',
                'updated_at' => '2023-10-02 13:07:30',
            ),
            61 => 
            array (
                'id' => 62,
                'booking_id' => 140,
                'service_id' => 72,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The restaurant and cafe sanitization service ensured a clean and safe dining experience. 👏🏻',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 06:43:07',
                'updated_at' => '2023-10-02 06:43:07',
            ),
            62 => 
            array (
                'id' => 63,
                'booking_id' => 139,
                'service_id' => 88,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The Special Occasion Styling Service elevated our look and made our event memorable. 👏🏻🥰🔥',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 06:44:34',
                'updated_at' => '2023-10-02 06:44:34',
            ),
            63 => 
            array (
                'id' => 64,
                'booking_id' => 138,
                'service_id' => 66,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The water heater installation service 🤗 was swift and professional, providing hot water when we needed it. ☺️',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 06:46:24',
                'updated_at' => '2023-10-02 06:47:19',
            ),
            64 => 
            array (
                'id' => 65,
                'booking_id' => 137,
                'service_id' => 43,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The roach control service 🪳🪲effectively eliminated pests, bringing peace to our home. 🕷️',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 06:48:19',
                'updated_at' => '2023-10-02 06:48:19',
            ),
            65 => 
            array (
                'id' => 66,
                'booking_id' => 136,
                'service_id' => 42,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The Satyanarayan Katha 🙏🏻service 🌺 was a spiritually enriching experience. 🔥',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 06:50:58',
                'updated_at' => '2023-10-02 06:50:58',
            ),
            66 => 
            array (
                'id' => 67,
                'booking_id' => 135,
                'service_id' => 79,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The custom frame painting 🖼️ service added a unique touch of art to our space. 🌄🏞️',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 06:52:31',
                'updated_at' => '2023-10-02 06:52:42',
            ),
            67 => 
            array (
                'id' => 68,
                'booking_id' => 134,
                'service_id' => 74,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The delicate garment 👚👕👗cleaning service was meticulous and careful, handling our attire with expertise. 🥻',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 06:53:46',
                'updated_at' => '2023-10-02 06:53:46',
            ),
            68 => 
            array (
                'id' => 69,
                'booking_id' => 133,
                'service_id' => 30,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The outdoor lighting 🏮💡 setup service enhanced our space with a warm and inviting ambiance. 🤩',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 06:56:10',
                'updated_at' => '2023-10-02 06:56:10',
            ),
            69 => 
            array (
                'id' => 70,
                'booking_id' => 131,
                'service_id' => 26,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The Chinese food service 🍝🍜👨‍🍳 satisfied our cravings with delicious and authentic dishes. 🥰',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 06:57:37',
                'updated_at' => '2023-10-02 06:57:49',
            ),
            70 => 
            array (
                'id' => 71,
                'booking_id' => 130,
                'service_id' => 21,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Our curtains look refreshed and clean after the service. Satisfied with the results. 😍🧼🧽',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 07:01:57',
                'updated_at' => '2023-10-02 07:02:56',
            ),
            71 => 
            array (
                'id' => 72,
                'booking_id' => 129,
                'service_id' => 15,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The wooden chair restoration 🪑 service revived our furniture beautifully, preserving its history.  😍',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 07:03:36',
                'updated_at' => '2023-10-02 07:04:17',
            ),
            72 => 
            array (
                'id' => 73,
                'booking_id' => 128,
                'service_id' => 31,
                'customer_id' => 3,
                'rating' => 3.0,
                'review' => 'The engine diagnostics service provided valuable insights, resolving issues with precision. 😌',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 07:05:08',
                'updated_at' => '2023-10-02 07:05:23',
            ),
            73 => 
            array (
                'id' => 74,
                'booking_id' => 144,
                'service_id' => 41,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The patchwork and fabric 👘🧥 repair service breathed new life into my cherished items. 🤩',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 07:11:41',
                'updated_at' => '2023-10-02 07:11:41',
            ),
            74 => 
            array (
                'id' => 75,
                'booking_id' => 145,
                'service_id' => 58,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Our appliances work seamlessly after the smart integration service, making life more convenient. 🥰',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 07:30:12',
                'updated_at' => '2023-10-02 07:30:12',
            ),
            75 => 
            array (
                'id' => 76,
                'booking_id' => 146,
                'service_id' => 67,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Thorough and detailed office sanitization service. Our workspace is now clean and safe. 😊',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 07:38:21',
                'updated_at' => '2023-10-02 07:38:21',
            ),
            76 => 
            array (
                'id' => 77,
                'booking_id' => 147,
                'service_id' => 78,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Creative and stylish nail art 💅🏻 that exceeded my expectations. I\'m thrilled with the results! 🥰',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 07:45:04',
                'updated_at' => '2023-10-02 07:45:04',
            ),
            77 => 
            array (
                'id' => 78,
                'booking_id' => 148,
                'service_id' => 60,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Timely and efficient drain cleaning – problem solved! 🤩',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 09:37:53',
                'updated_at' => '2023-10-02 09:37:53',
            ),
            78 => 
            array (
                'id' => 79,
                'booking_id' => 149,
                'service_id' => 77,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The murals and wall art 👨‍🎨 service transformed our space beautifully, adding a touch of creativity. 🥰',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 09:48:20',
                'updated_at' => '2023-10-02 09:48:33',
            ),
            79 => 
            array (
                'id' => 80,
                'booking_id' => 150,
                'service_id' => 48,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Efficient and hassle-free clothing wash and fold service that simplifies my life. 👚👕👔',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 09:53:32',
                'updated_at' => '2023-10-02 09:53:32',
            ),
            80 => 
            array (
                'id' => 81,
                'booking_id' => 151,
                'service_id' => 29,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The indoor lighting installation was expertly executed, illuminating our space brilliantly. 🏮💡',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 10:01:40',
                'updated_at' => '2023-10-02 10:01:40',
            ),
            81 => 
            array (
                'id' => 82,
                'booking_id' => 152,
                'service_id' => 25,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The authentic Mexican cuisine 🌮🌯🍔 prepared by the chef was a delicious journey to Mexico itself. A culinary delight! 🌭',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 10:08:18',
                'updated_at' => '2023-10-02 10:08:33',
            ),
            82 => 
            array (
                'id' => 83,
                'booking_id' => 153,
                'service_id' => 20,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Great carpet cleaning! Our carpets look refreshed, and we\'re pleased with the service. 🧹🧽🧼🪥',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 10:19:39',
                'updated_at' => '2023-10-02 10:19:39',
            ),
            83 => 
            array (
                'id' => 84,
                'booking_id' => 154,
                'service_id' => 14,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Efficient tire rotation and balancing that improved my car\'s performance. 🚙🥰',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 10:31:20',
                'updated_at' => '2023-10-02 10:31:20',
            ),
            84 => 
            array (
                'id' => 85,
                'booking_id' => 155,
                'service_id' => 36,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'AC tune-up service was thorough and improved our system\'s performance noticeably. 🛠️🪛',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 10:48:11',
                'updated_at' => '2023-10-02 10:48:11',
            ),
            85 => 
            array (
                'id' => 86,
                'booking_id' => 156,
                'service_id' => 12,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Efficient window AC installation, quickly cooling our space. 🛠️🪛',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 11:39:59',
                'updated_at' => '2023-10-02 11:39:59',
            ),
            86 => 
            array (
                'id' => 87,
                'booking_id' => 157,
                'service_id' => 13,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Thorough window oil change and fluid checks, essential for my car\'s well-being. 🛠️🥰',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 11:49:21',
                'updated_at' => '2023-10-02 11:49:21',
            ),
            87 => 
            array (
                'id' => 88,
                'booking_id' => 158,
                'service_id' => 19,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Thorough cleaning of ceilings and walls, restoring the freshness of our space. 🧹🧼🧽',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 11:55:09',
                'updated_at' => '2023-10-02 11:55:09',
            ),
            88 => 
            array (
                'id' => 89,
                'booking_id' => 159,
                'service_id' => 24,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The family-style dinner prepared by the chef was a delightful feast, leaving us satisfied and content. 🌯🥪🍜🍲',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 12:05:12',
                'updated_at' => '2023-10-02 12:05:12',
            ),
            89 => 
            array (
                'id' => 90,
                'booking_id' => 160,
                'service_id' => 28,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Efficient wiring repair, solving our electrical issues promptly. 🪛🛠️',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 12:11:50',
                'updated_at' => '2023-10-02 12:11:50',
            ),
            90 => 
            array (
                'id' => 91,
                'booking_id' => 161,
                'service_id' => 61,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Flawless hair coloring, transforming my look beautifully. 🤩',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 12:19:37',
                'updated_at' => '2023-10-02 12:19:37',
            ),
            91 => 
            array (
                'id' => 92,
                'booking_id' => 162,
                'service_id' => 75,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Thorough whole-house exterior painting, a job well done on our property. 😍',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 12:26:28',
                'updated_at' => '2023-10-02 12:26:28',
            ),
            92 => 
            array (
                'id' => 93,
                'booking_id' => 164,
                'service_id' => 53,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Efficient pipe bursting repair, quickly resolving our plumbing issue. 🪛🛠️',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 12:34:43',
                'updated_at' => '2023-10-02 12:34:43',
            ),
            93 => 
            array (
                'id' => 94,
                'booking_id' => 165,
                'service_id' => 64,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Efficient color touch-ups and maintenance, keeping our space vibrant. 😍🤩',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 12:39:58',
                'updated_at' => '2023-10-02 12:39:58',
            ),
            94 => 
            array (
                'id' => 95,
                'booking_id' => 166,
                'service_id' => 54,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Efficient high-touch point disinfection, ensuring a safe environment. 🤩😊🥰',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 12:46:01',
                'updated_at' => '2023-10-02 12:46:01',
            ),
            95 => 
            array (
                'id' => 96,
                'booking_id' => 167,
                'service_id' => 56,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Efficient smart lighting installation, simplifying our home lighting. 🏮💡',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 12:50:07',
                'updated_at' => '2023-10-02 12:50:07',
            ),
            96 => 
            array (
                'id' => 97,
                'booking_id' => 168,
                'service_id' => 39,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Efficient garment restoration, saving my treasured clothing pieces. 🧥👘🥻',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 13:01:05',
                'updated_at' => '2023-10-02 13:02:14',
            ),
            97 => 
            array (
                'id' => 98,
                'booking_id' => 169,
                'service_id' => 40,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Efficient home theater setup, making our movie nights even better. 🤩😍',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 13:06:03',
                'updated_at' => '2023-10-02 13:06:03',
            ),
            98 => 
            array (
                'id' => 99,
                'booking_id' => 170,
                'service_id' => 45,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Personalized facials that left my skin glowing and refreshed. 🧖',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 13:12:59',
                'updated_at' => '2023-10-02 13:12:59',
            ),
            99 => 
            array (
                'id' => 100,
                'booking_id' => 171,
                'service_id' => 50,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Efficient whole-room painting, truly refreshing our space. 🖌️😍',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 13:19:38',
                'updated_at' => '2023-10-02 13:19:38',
            ),
            100 => 
            array (
                'id' => 101,
                'booking_id' => 172,
                'service_id' => 23,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Efficient daily meal preparation, keeping us well-fed and satisfied. 🥪🍲👩🏻‍🍳',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 13:27:27',
                'updated_at' => '2023-10-02 13:28:26',
            ),
            101 => 
            array (
                'id' => 102,
                'booking_id' => 173,
                'service_id' => 18,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Efficient full house cleaning, leaving every corner refreshed.🧹🧼🧽',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 13:33:58',
                'updated_at' => '2023-10-02 13:33:58',
            ),
            102 => 
            array (
                'id' => 103,
                'booking_id' => 65,
                'service_id' => 63,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The bed bug removal was carried out diligently, making our space bug-free. 🤩',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 13:37:18',
                'updated_at' => '2023-10-02 13:37:18',
            ),
            103 => 
            array (
                'id' => 104,
                'booking_id' => 60,
                'service_id' => 83,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Outstanding pest management for drainage systems! Their expertise and thoroughness in eliminating pests were truly impressive. A job well done! 😍',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 13:38:50',
                'updated_at' => '2023-10-02 13:38:50',
            ),
            104 => 
            array (
                'id' => 105,
                'booking_id' => 58,
                'service_id' => 78,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Nail art that reflects true craftsmanship and attention to detail. I\'m genuinely pleased with the outcome. 💅😍',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 13:40:01',
                'updated_at' => '2023-10-02 13:40:01',
            ),
            105 => 
            array (
                'id' => 106,
                'booking_id' => 57,
                'service_id' => 72,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Our eatery\'s hygiene was maintained meticulously, creating a secure environment. 😊🥰',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 13:41:00',
                'updated_at' => '2023-10-02 13:41:00',
            ),
            106 => 
            array (
                'id' => 107,
                'booking_id' => 55,
                'service_id' => 96,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Exceptional attention to detail! The manicure and pedicure service exceeded my expectations. I\'m walking on air with my 5-star nails! 🥰🤩',
                'deleted_at' => NULL,
                'created_at' => '2023-10-02 13:43:04',
                'updated_at' => '2023-10-02 13:43:04',
            ),
            107 => 
            array (
                'id' => 108,
                'booking_id' => 178,
                'service_id' => 104,
                'customer_id' => 50,
                'rating' => 4.0,
                'review' => 'Our clothing was expertly repaired and reinforced, extending their lifespan. 🪡🧵',
                'deleted_at' => NULL,
                'created_at' => '2023-10-03 12:20:41',
                'updated_at' => '2023-10-03 12:20:41',
            ),
            108 => 
            array (
                'id' => 109,
                'booking_id' => 179,
                'service_id' => 110,
                'customer_id' => 50,
                'rating' => 4.0,
                'review' => 'Outstanding filter replacement! The technician\'s expertise and efficiency were impressive. 😄',
                'deleted_at' => NULL,
                'created_at' => '2023-10-03 12:25:01',
                'updated_at' => '2023-10-03 12:25:01',
            ),
            109 => 
            array (
                'id' => 110,
                'booking_id' => 180,
                'service_id' => 100,
                'customer_id' => 49,
                'rating' => 4.0,
                'review' => 'Outstanding attention to detail in frame design! The artistic flair and craftsmanship were exceptional. Highly recommended! 🖌️',
                'deleted_at' => NULL,
                'created_at' => '2023-10-03 12:34:39',
                'updated_at' => '2023-10-03 12:34:39',
            ),
            110 => 
            array (
                'id' => 111,
                'booking_id' => 181,
                'service_id' => 110,
                'customer_id' => 48,
                'rating' => 5.0,
                'review' => 'Impressed by the skill and dedication in filter replacement. 🪛🛠️A 5-star rating well earned!',
                'deleted_at' => NULL,
                'created_at' => '2023-10-03 12:40:45',
                'updated_at' => '2023-10-03 12:40:45',
            ),
            111 => 
            array (
                'id' => 112,
                'booking_id' => 182,
                'service_id' => 107,
                'customer_id' => 48,
                'rating' => 4.0,
                'review' => 'Outstanding attention to detail in office cleaning! The team\'s professionalism and thoroughness were impressive. 🧹🥰',
                'deleted_at' => NULL,
                'created_at' => '2023-10-03 13:07:55',
                'updated_at' => '2023-10-03 13:08:06',
            ),
            112 => 
            array (
                'id' => 113,
                'booking_id' => 183,
                'service_id' => 104,
                'customer_id' => 47,
                'rating' => 5.0,
                'review' => 'The service addressed the wear and tear issues effectively. 🥰😍🧵🧹',
                'deleted_at' => NULL,
                'created_at' => '2023-10-03 13:11:47',
                'updated_at' => '2023-10-03 13:12:00',
            ),
            113 => 
            array (
                'id' => 114,
                'booking_id' => 184,
                'service_id' => 107,
                'customer_id' => 46,
                'rating' => 5.0,
                'review' => 'Impressed by the dedication and efficiency in office cleaning service. 🧹 A 5-star rating well earned! 😍',
                'deleted_at' => NULL,
                'created_at' => '2023-10-03 13:17:01',
                'updated_at' => '2023-10-03 13:17:24',
            ),
            114 => 
            array (
                'id' => 115,
                'booking_id' => 186,
                'service_id' => 110,
                'customer_id' => 41,
                'rating' => 5.0,
                'review' => 'The quality of work and improved air quality are exceptional, earning them a solid 5 stars. 🌞',
                'deleted_at' => NULL,
                'created_at' => '2023-10-05 06:03:22',
                'updated_at' => '2023-10-05 06:03:22',
            ),
            115 => 
            array (
                'id' => 116,
                'booking_id' => 187,
                'service_id' => 100,
                'customer_id' => 40,
                'rating' => 5.0,
                'review' => 'Top-notch frame design service! Our pieces look stunning and are beautifully showcased. Exceptional work! 🖼️',
                'deleted_at' => NULL,
                'created_at' => '2023-10-05 06:09:52',
                'updated_at' => '2023-10-05 06:09:52',
            ),
            116 => 
            array (
                'id' => 117,
                'booking_id' => 188,
                'service_id' => 104,
                'customer_id' => 39,
                'rating' => 4.0,
                'review' => 'Efficient seam repair and reinforcement improved the durability of our items. 🪡👘🥻',
                'deleted_at' => NULL,
                'created_at' => '2023-10-05 06:15:41',
                'updated_at' => '2023-10-05 06:15:41',
            ),
            117 => 
            array (
                'id' => 118,
                'booking_id' => 189,
                'service_id' => 110,
                'customer_id' => 39,
                'rating' => 4.0,
                'review' => 'Reliable and top-notch filter replacement. Our home environment is noticeably healthier. 🥰😍',
                'deleted_at' => NULL,
                'created_at' => '2023-10-05 06:19:36',
                'updated_at' => '2023-10-05 06:19:36',
            ),
            118 => 
            array (
                'id' => 119,
                'booking_id' => 190,
                'service_id' => 110,
                'customer_id' => 38,
                'rating' => 4.0,
                'review' => 'Efficient AC filter replacement, ensuring cool, clean air in no time. 🪛🛠️',
                'deleted_at' => NULL,
                'created_at' => '2023-10-05 06:37:26',
                'updated_at' => '2023-10-05 06:37:26',
            ),
            119 => 
            array (
                'id' => 120,
                'booking_id' => 191,
                'service_id' => 104,
                'customer_id' => 38,
                'rating' => 4.0,
                'review' => 'Clothing repairs were skillfully handled, ensuring they stay in good condition. 👗👕👖👔',
                'deleted_at' => NULL,
                'created_at' => '2023-10-05 06:38:33',
                'updated_at' => '2023-10-05 06:39:04',
            ),
            120 => 
            array (
                'id' => 121,
                'booking_id' => 193,
                'service_id' => 107,
                'customer_id' => 37,
                'rating' => 5.0,
                'review' => 'Flawless office cleaning! The quality of work and cleanliness are exceptional, earning them a solid 5 stars. 🧹🧼',
                'deleted_at' => NULL,
                'created_at' => '2023-10-05 06:51:09',
                'updated_at' => '2023-10-05 06:51:09',
            ),
            121 => 
            array (
                'id' => 122,
                'booking_id' => 194,
                'service_id' => 97,
                'customer_id' => 48,
                'rating' => 4.0,
                'review' => 'Outstanding compressor repair! The technician\'s expertise and timely service were impressive. Definitely deserving of a 5-star review. 🛠️🪛',
                'deleted_at' => NULL,
                'created_at' => '2023-10-05 07:11:02',
                'updated_at' => '2023-10-05 07:11:02',
            ),
            122 => 
            array (
                'id' => 123,
                'booking_id' => 195,
                'service_id' => 26,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Our meal was a delightful journey to China, thanks to the chef\'s culinary expertise. 🍜🍝',
                'deleted_at' => NULL,
                'created_at' => '2023-10-05 07:19:47',
                'updated_at' => '2023-10-05 07:19:47',
            ),
            123 => 
            array (
                'id' => 124,
                'booking_id' => 197,
                'service_id' => 81,
                'customer_id' => 50,
                'rating' => 4.0,
                'review' => 'Our walls were transformed into a gallery of art, thanks to the painter\'s talent. 🖼️',
                'deleted_at' => NULL,
                'created_at' => '2023-10-05 07:29:42',
                'updated_at' => '2023-10-05 07:29:42',
            ),
            124 => 
            array (
                'id' => 125,
                'booking_id' => 199,
                'service_id' => 15,
                'customer_id' => 49,
                'rating' => 4.0,
                'review' => 'Our chairs received expert care, showcasing their true vintage charm. 🪑🪚',
                'deleted_at' => NULL,
                'created_at' => '2023-10-05 07:37:32',
                'updated_at' => '2023-10-05 07:37:32',
            ),
            125 => 
            array (
                'id' => 126,
                'booking_id' => 201,
                'service_id' => 105,
                'customer_id' => 47,
                'rating' => 4.0,
                'review' => 'Outstanding custom cake 🎂🧁🍰 design! The chef\'s creativity and attention to detail made our celebration unforgettable. 😍',
                'deleted_at' => NULL,
                'created_at' => '2023-10-05 08:13:17',
                'updated_at' => '2023-10-05 08:13:17',
            ),
            126 => 
            array (
                'id' => 127,
                'booking_id' => 202,
                'service_id' => 35,
                'customer_id' => 43,
                'rating' => 5.0,
                'review' => 'Well-handled cleaning service, greatly appreciated for the thoroughness. 🧹🧼🧽',
                'deleted_at' => NULL,
                'created_at' => '2023-10-05 08:21:45',
                'updated_at' => '2023-10-05 08:21:45',
            ),
            127 => 
            array (
                'id' => 128,
                'booking_id' => 203,
                'service_id' => 80,
                'customer_id' => 46,
                'rating' => 4.0,
                'review' => 'Outstanding service for cleaning evening gowns and formal wear! My outfits look pristine, and the quality is unmatched. 🥰🌞',
                'deleted_at' => NULL,
                'created_at' => '2023-10-05 09:21:28',
                'updated_at' => '2023-10-05 09:21:28',
            ),
            128 => 
            array (
                'id' => 129,
                'booking_id' => 207,
                'service_id' => 94,
                'customer_id' => 44,
                'rating' => 4.0,
                'review' => 'Our styling needs were met with creativity and professionalism. 💇🏻‍♀️',
                'deleted_at' => NULL,
                'created_at' => '2023-10-05 10:08:31',
                'updated_at' => '2023-10-05 10:08:31',
            ),
            129 => 
            array (
                'id' => 130,
                'booking_id' => 208,
                'service_id' => 110,
                'customer_id' => 45,
                'rating' => 5.0,
                'review' => 'Professional service, keeping our AC running smoothly with expertise. 🤩',
                'deleted_at' => NULL,
                'created_at' => '2023-10-05 10:13:06',
                'updated_at' => '2023-10-05 10:13:06',
            ),
            130 => 
            array (
                'id' => 131,
                'booking_id' => 209,
                'service_id' => 101,
                'customer_id' => 42,
                'rating' => 5.0,
                'review' => 'The leak repair service quickly resolved the issue, preventing further damage. 😍',
                'deleted_at' => NULL,
                'created_at' => '2023-10-05 10:16:45',
                'updated_at' => '2023-10-05 10:16:45',
            ),
        ));
        
        
    }
}