<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class HandymanRatingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('handyman_ratings')->delete();
        
        \DB::table('handyman_ratings')->insert(array (
            0 => 
            array (
                'id' => 1,
                'booking_id' => 35,
                'service_id' => 11,
                'handyman_id' => 24,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The Split AC setup was impeccable, thank you for your expertise! 😍',
                'created_at' => '2023-09-12 06:41:25',
                'updated_at' => '2023-09-12 06:41:25',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'booking_id' => 105,
                'service_id' => 70,
                'handyman_id' => 32,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Exceptional taste and style – this clothing service worker knows contemporary fashion inside out. 5☀️',
                'created_at' => '2023-09-29 09:47:43',
                'updated_at' => '2023-09-29 09:47:43',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'booking_id' => 104,
                'service_id' => 98,
                'handyman_id' => 25,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Exceptional security camera setup service! The technician was highly skilled, and my system works flawlessly. A solid 5-star rating. ❤️',
                'created_at' => '2023-09-29 09:50:07',
                'updated_at' => '2023-09-29 09:50:15',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'booking_id' => 103,
                'service_id' => 68,
                'handyman_id' => 21,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Dedicated and vigilant; our residential security patrol worker is a true asset. 4 stars!❤️',
                'created_at' => '2023-09-29 09:54:06',
                'updated_at' => '2023-09-29 09:54:06',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'booking_id' => 102,
                'service_id' => 95,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Exceptional job by the car interior sanitization technician! My car feels brand new, and I\'m giving a well-deserved 5-star rating. ❤️',
                'created_at' => '2023-09-29 09:57:35',
                'updated_at' => '2023-09-29 09:57:35',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'booking_id' => 101,
                'service_id' => 96,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Exceptional manicure and pedicure service! Impeccable attention to detail and a relaxing experience. 🥰😍',
                'created_at' => '2023-09-29 10:01:09',
                'updated_at' => '2023-09-29 10:01:09',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'booking_id' => 100,
                'service_id' => 108,
                'handyman_id' => 20,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Exceptional plumbing service! The fixture installation was done flawlessly, and the plumber was courteous. 😍🛠️😊',
                'created_at' => '2023-09-29 10:06:06',
                'updated_at' => '2023-09-29 10:06:06',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'booking_id' => 99,
                'service_id' => 73,
                'handyman_id' => 22,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Absolutely stunning wedding photos! The photographer captured every precious moment perfectly.  📸🥰',
                'created_at' => '2023-09-29 10:11:02',
                'updated_at' => '2023-09-29 10:11:02',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'booking_id' => 98,
                'service_id' => 65,
                'handyman_id' => 19,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Exceptional rodent trapping expertise! The worker was quick, thorough, and solved our pest problem. 😍😊❤️',
                'created_at' => '2023-09-29 10:17:58',
                'updated_at' => '2023-09-29 10:17:58',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'booking_id' => 97,
                'service_id' => 62,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Invaluable career and finance advice! The consultation was enlightening, and I feel more confident about my future. 😍😎😇',
                'created_at' => '2023-09-29 10:23:59',
                'updated_at' => '2023-09-29 10:23:59',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'booking_id' => 96,
                'service_id' => 91,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Exceptional custom stenciling craftsmanship! Attention to detail and creativity shone through. 🥰😊',
                'created_at' => '2023-09-29 10:26:42',
                'updated_at' => '2023-09-29 10:26:42',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'booking_id' => 95,
                'service_id' => 80,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Exceptional evening gown and formal attire cleaning! My dresses look brand new, and the service was impeccable. 🥰😇',
                'created_at' => '2023-09-29 11:06:04',
                'updated_at' => '2023-09-29 11:06:04',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'booking_id' => 94,
                'service_id' => 49,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Exceptional lawn care! The mowing and trimming service was top-notch, and our yard looks pristine.😇',
                'created_at' => '2023-09-29 11:38:00',
                'updated_at' => '2023-09-29 11:38:00',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'booking_id' => 93,
                'service_id' => 99,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Exceptional circuit repair service! The technician resolved the issue swiftly, and our electrical system is back in top shape.😊🛠️',
                'created_at' => '2023-09-29 11:40:22',
                'updated_at' => '2023-09-29 11:40:22',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'booking_id' => 92,
                'service_id' => 46,
                'handyman_id' => 18,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Exceptional dessert chef! Their sweet creations were pure artistry, and the taste was heavenly. 🥞🧇🥯🥐',
                'created_at' => '2023-09-29 11:42:57',
                'updated_at' => '2023-09-29 11:42:57',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'booking_id' => 91,
                'service_id' => 35,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Exceptional kitchen and bathroom deep cleaning! 😎 Every nook and cranny shines, and the service was thorough. 🧹🧽🧼',
                'created_at' => '2023-09-29 11:50:35',
                'updated_at' => '2023-09-29 11:50:43',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'booking_id' => 90,
                'service_id' => 17,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Exceptional beam and column installation! The craftsmanship and precision exceeded our expectations.😎🪛🔩',
                'created_at' => '2023-09-29 11:51:47',
                'updated_at' => '2023-09-29 11:51:53',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'booking_id' => 89,
                'service_id' => 33,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Exceptional transmission repair service! Quick, efficient, and our vehicle runs like new. 🛠️🤩🪛',
                'created_at' => '2023-09-29 11:53:11',
                'updated_at' => '2023-09-29 11:53:11',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'booking_id' => 88,
                'service_id' => 97,
                'handyman_id' => 36,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Exceptional compressor fix service! ?️Swift, skilled, and our equipment works like new. 🪛😍',
                'created_at' => '2023-09-29 11:54:09',
                'updated_at' => '2023-09-29 11:54:21',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'booking_id' => 87,
                'service_id' => 110,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Exceptional filter replacement service! 🪛🔧 Quick and efficient, our air quality has improved noticeably. 🤩',
                'created_at' => '2023-09-29 11:56:22',
                'updated_at' => '2023-09-29 11:56:35',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'booking_id' => 86,
                'service_id' => 38,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'My car\'s finish is now better than new. A solid 5-star rating!  🥰🤩',
                'created_at' => '2023-09-29 12:03:31',
                'updated_at' => '2023-09-29 12:03:31',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'booking_id' => 85,
                'service_id' => 34,
                'handyman_id' => 34,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Precision and craftsmanship at its finest. A solid 4-star rating! ❤️😍',
                'created_at' => '2023-09-29 12:04:30',
                'updated_at' => '2023-09-29 12:04:30',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'booking_id' => 84,
                'service_id' => 107,
                'handyman_id' => 4,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The workspace shines, and the service was professional. 🧼🧽🪣🧹',
                'created_at' => '2023-09-29 12:05:37',
                'updated_at' => '2023-09-29 12:05:37',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'booking_id' => 80,
                'service_id' => 105,
                'handyman_id' => 31,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The chef\'s artistry and taste were beyond exquisite. A solid 5-star rating! 😍🍰🍮',
                'created_at' => '2023-09-29 12:06:44',
                'updated_at' => '2023-09-29 12:06:44',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'booking_id' => 79,
                'service_id' => 106,
                'handyman_id' => 21,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Impressive electrical wiring installation! 🛠️🪛 The technician\'s attention to detail and professionalism were truly commendable. 🤩🥰',
                'created_at' => '2023-09-29 12:22:25',
                'updated_at' => '2023-09-29 12:22:25',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'booking_id' => 78,
                'service_id' => 86,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Impressive pruning and trimming service! 🌾 Our garden looks perfectly manicured, thanks to their expertise. Highly recommended! 🤩🥰',
                'created_at' => '2023-09-29 12:26:07',
                'updated_at' => '2023-09-29 12:26:07',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'booking_id' => 77,
                'service_id' => 92,
                'handyman_id' => 27,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Impressed by the impeccable leather and suede cleaning! 🧥 My items look refreshed and pristine. Kudos on a job well done! 🤩',
                'created_at' => '2023-09-29 12:27:53',
                'updated_at' => '2023-09-29 12:27:53',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'booking_id' => 75,
                'service_id' => 100,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The artist\'s creativity and craftsmanship were exceptional. Highly recommended! 🖌️🎨',
                'created_at' => '2023-09-29 12:29:21',
                'updated_at' => '2023-09-29 12:29:21',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'booking_id' => 74,
                'service_id' => 84,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Incredibly insightful compatibility reading! The worker\'s expertise brought clarity to our relationship. Highly recommend! 😊',
                'created_at' => '2023-09-29 12:30:34',
                'updated_at' => '2023-09-29 12:30:34',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'booking_id' => 73,
                'service_id' => 83,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Impressive pest management for our drainage system! The technician\'s expertise eliminated our pest issue effectively. Highly recommended! 😍',
                'created_at' => '2023-09-29 12:31:34',
                'updated_at' => '2023-09-29 12:31:40',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'booking_id' => 72,
                'service_id' => 82,
                'handyman_id' => 36,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Your photography skills brought our corporate event to life! The moments you captured are priceless. Thank you! 😍📸',
                'created_at' => '2023-09-29 12:33:16',
                'updated_at' => '2023-09-29 12:33:16',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'booking_id' => 71,
                'service_id' => 108,
                'handyman_id' => 20,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Outstanding fixture installation service! 🛠️🪛 The plumber was professional, efficient, and left everything spotless. ❤️🔩',
                'created_at' => '2023-09-29 12:35:47',
                'updated_at' => '2023-09-29 12:36:03',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'booking_id' => 70,
                'service_id' => 102,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The exfoliation and peel service left my skin rejuvenated and glowing. 🧖 Thank you for the skincare transformation! 😍🤩',
                'created_at' => '2023-09-29 12:57:55',
                'updated_at' => '2023-09-29 12:57:55',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'booking_id' => 69,
                'service_id' => 109,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Thorough full home sanitization service! Our living space feels clean and safe. 🤩',
                'created_at' => '2023-09-29 13:06:19',
                'updated_at' => '2023-09-29 13:06:19',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'booking_id' => 68,
                'service_id' => 90,
                'handyman_id' => 24,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The commercial building service worker consistently delivered quality results. 😍👮🏻‍♀️',
                'created_at' => '2023-09-29 13:07:30',
                'updated_at' => '2023-09-29 13:07:52',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'booking_id' => 67,
                'service_id' => 103,
                'handyman_id' => 15,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The smart TV integration service made our entertainment setup seamless and hassle-free. 🪛🤩🛠️',
                'created_at' => '2023-09-29 13:08:51',
                'updated_at' => '2023-09-29 13:08:59',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'booking_id' => 66,
                'service_id' => 104,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Skillful work on seam repair and reinforcement. Our clothes are now ready to face wear and tear.🧶🧵🪡🥰',
                'created_at' => '2023-09-29 13:10:10',
                'updated_at' => '2023-09-29 13:10:23',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'booking_id' => 106,
                'service_id' => 101,
                'handyman_id' => 28,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The leak repair service efficiently resolved our issue, preventing further damage. 🪛🛠️🔩🥰',
                'created_at' => '2023-09-29 13:18:12',
                'updated_at' => '2023-09-29 13:18:12',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'booking_id' => 108,
                'service_id' => 59,
                'handyman_id' => 33,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The tailor\'s work on our bespoke suits and dresses was skillful and precise, exceeding our expectations. 👔🧥🥻👘',
                'created_at' => '2023-09-29 14:11:52',
                'updated_at' => '2023-09-29 14:11:52',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'booking_id' => 109,
                'service_id' => 71,
                'handyman_id' => 31,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Efficiently installed our alarm system, ensuring security without hassle. ❤️🥰',
                'created_at' => '2023-09-29 14:12:38',
                'updated_at' => '2023-09-29 14:12:38',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'booking_id' => 110,
                'service_id' => 55,
                'handyman_id' => 29,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The VIP escort protection worker ensured our safety with unwavering dedication and professionalism. 👮🏻👮🏻‍♀️',
                'created_at' => '2023-09-29 14:13:24',
                'updated_at' => '2023-09-29 14:13:24',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'booking_id' => 127,
                'service_id' => 37,
                'handyman_id' => 36,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The handyman\'s AC coolant renewal service rejuvenated our cooling system efficiently.🪛🛠️',
                'created_at' => '2023-09-30 07:46:35',
                'updated_at' => '2023-09-30 07:46:43',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'booking_id' => 126,
                'service_id' => 93,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The handyman\'s AC airflow problem identification service was a lifesaver in the heat. 😍',
                'created_at' => '2023-09-30 07:47:50',
                'updated_at' => '2023-09-30 07:47:50',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'booking_id' => 124,
                'service_id' => 32,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The worker\'s interior car cleaning and care service made my vehicle feel fresh and well-maintained. 🚗🚙🚗💕',
                'created_at' => '2023-09-30 07:49:04',
                'updated_at' => '2023-09-30 07:49:19',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'booking_id' => 123,
                'service_id' => 16,
                'handyman_id' => 26,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The carpenter\'s cabinet fix and refinish service transformed our cabinets with skill and care. 🛠️😍',
                'created_at' => '2023-09-30 07:57:27',
                'updated_at' => '2023-09-30 07:57:27',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'booking_id' => 122,
                'service_id' => 22,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The chimney sweeping service worker did a meticulous job, ensuring our safety. 🧹🧽🧼',
                'created_at' => '2023-09-30 07:58:37',
                'updated_at' => '2023-09-30 07:58:37',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'booking_id' => 121,
                'service_id' => 27,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The Italian cook service by the Italian chef delighted our taste buds with authentic flavors. 🍕🥘🍝',
                'created_at' => '2023-09-30 08:00:14',
                'updated_at' => '2023-09-30 08:00:14',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'booking_id' => 120,
                'service_id' => 85,
                'handyman_id' => 23,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The electrician\'s fault diagnosis service was invaluable, swiftly resolving our electrical issues..🪛🛠️',
                'created_at' => '2023-09-30 09:29:17',
                'updated_at' => '2023-09-30 09:29:17',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'booking_id' => 119,
                'service_id' => 47,
                'handyman_id' => 24,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The Green Space Guardians service helped our garden thrive with expertise and dedication.😍🌾🌿',
                'created_at' => '2023-09-30 09:30:46',
                'updated_at' => '2023-09-30 09:30:46',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'booking_id' => 118,
                'service_id' => 76,
                'handyman_id' => 29,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The care and attention given to my silk garments were much appreciated. 👘🥻',
                'created_at' => '2023-09-30 09:31:36',
                'updated_at' => '2023-09-30 09:31:36',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'booking_id' => 117,
                'service_id' => 81,
                'handyman_id' => 33,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The multi-frame set painting service brought our walls to life with creativity and style. 🖼️🖌️🎨',
                'created_at' => '2023-09-30 09:33:09',
                'updated_at' => '2023-09-30 09:34:02',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'booking_id' => 116,
                'service_id' => 51,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The pandit\'s expertise and devotion during our marriage puja were truly remarkable. 🔥',
                'created_at' => '2023-09-30 09:36:05',
                'updated_at' => '2023-09-30 09:36:05',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'booking_id' => 115,
                'service_id' => 63,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The bed bug eradication service effectively rid our space of pests, restoring comfort. 😍🥰',
                'created_at' => '2023-09-30 09:39:44',
                'updated_at' => '2023-09-30 09:39:44',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'booking_id' => 114,
                'service_id' => 44,
                'handyman_id' => 31,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Our family portraits turned out beautifully, capturing cherished moments. 📸😍',
                'created_at' => '2023-09-30 09:40:52',
                'updated_at' => '2023-09-30 09:40:52',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'booking_id' => 113,
                'service_id' => 87,
                'handyman_id' => 36,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The sewer line cleaning worker efficiently resolved our plumbing issue. 🔥😍',
                'created_at' => '2023-09-30 09:41:50',
                'updated_at' => '2023-09-30 09:41:50',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'booking_id' => 112,
                'service_id' => 94,
                'handyman_id' => 35,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The stylist\'s work was a true confidence booster, leaving me satisfied. 💇🏻🥰😍',
                'created_at' => '2023-09-30 09:49:11',
                'updated_at' => '2023-09-30 09:49:11',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'booking_id' => 111,
                'service_id' => 89,
                'handyman_id' => 34,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The outdoor area sanitization worker diligently ensured a clean and safe environment. 👏🏻🔥',
                'created_at' => '2023-09-30 09:50:27',
                'updated_at' => '2023-09-30 09:50:27',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'booking_id' => 143,
                'service_id' => 57,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The tailor\'s hemming 👗👚👕👖 and length adjustment work was precise and meticulous. 😍',
                'created_at' => '2023-10-02 06:31:30',
                'updated_at' => '2023-10-02 06:31:39',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'booking_id' => 142,
                'service_id' => 69,
                'handyman_id' => 25,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Efficient smart lock installation 🔐 - our security is now modernized and convenient. 🥰',
                'created_at' => '2023-10-02 06:33:18',
                'updated_at' => '2023-10-02 06:33:18',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'booking_id' => 141,
                'service_id' => 52,
                'handyman_id' => 26,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The bodyguard service ?👮🏻‍♀️ ensured our safety discreetly and professionally. 🤩',
                'created_at' => '2023-10-02 06:42:05',
                'updated_at' => '2023-10-02 06:42:19',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'booking_id' => 140,
                'service_id' => 72,
                'handyman_id' => 28,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The restaurant and cafe sanitization service upheld hygiene standards with precision. 👏🏻🤩',
                'created_at' => '2023-10-02 06:43:32',
                'updated_at' => '2023-10-02 06:43:32',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'booking_id' => 139,
                'service_id' => 88,
                'handyman_id' => 33,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The hair stylist\'s styling 🤗 for our special occasion was perfect, enhancing our beauty effortlessly. 👸',
                'created_at' => '2023-10-02 06:45:44',
                'updated_at' => '2023-10-02 06:45:53',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'booking_id' => 138,
                'service_id' => 66,
                'handyman_id' => 23,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The water heater installation was handled with skill 😍 and professionalism, ensuring hot water for our home. 🤗🤩',
                'created_at' => '2023-10-02 06:46:44',
                'updated_at' => '2023-10-02 06:47:01',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'booking_id' => 137,
                'service_id' => 43,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The roach control service 🪳🪲efficiently eliminated pests, creating a pest-free environment. 🪰',
                'created_at' => '2023-10-02 06:48:55',
                'updated_at' => '2023-10-02 06:48:55',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'booking_id' => 136,
                'service_id' => 42,
                'handyman_id' => 29,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The Satyanarayan Katha 🙏🏻🌺service by the pandit brought spiritual blessings to our home. 🌹',
                'created_at' => '2023-10-02 06:51:40',
                'updated_at' => '2023-10-02 06:51:40',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'booking_id' => 135,
                'service_id' => 79,
                'handyman_id' => 24,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The custom frame painting service 🏞️🖼️ added a personalized touch to our decor, elevating its charm. 🌄',
                'created_at' => '2023-10-02 06:53:11',
                'updated_at' => '2023-10-02 06:53:11',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'booking_id' => 134,
                'service_id' => 74,
                'handyman_id' => 27,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The delicate garment 🥻👘🧥cleaning service handled our attire with care and finesse. 👗👔',
                'created_at' => '2023-10-02 06:54:54',
                'updated_at' => '2023-10-02 06:54:54',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'booking_id' => 133,
                'service_id' => 30,
                'handyman_id' => 19,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The outdoor lighting 🏮💡setup brought our landscape to life with skillful artistry. 🤩',
                'created_at' => '2023-10-02 06:56:35',
                'updated_at' => '2023-10-02 06:56:35',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'booking_id' => 131,
                'service_id' => 26,
                'handyman_id' => 32,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The Chinese food 🍜🍝 service by the Chinese chef 🧑‍🍳 delivered an authentic taste of China to our table. 🥰',
                'created_at' => '2023-10-02 06:58:40',
                'updated_at' => '2023-10-02 06:58:40',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'booking_id' => 130,
                'service_id' => 21,
                'handyman_id' => 19,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The curtain cleaning service left our curtains refreshed and spotless. 🧼🧽🤗',
                'created_at' => '2023-10-02 07:02:49',
                'updated_at' => '2023-10-02 07:03:05',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'booking_id' => 129,
                'service_id' => 15,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The wooden chair restoration 🪑 service by the carpenter breathed new life into our cherished furniture. 🤗',
                'created_at' => '2023-10-02 07:04:40',
                'updated_at' => '2023-10-02 07:04:40',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'booking_id' => 128,
                'service_id' => 31,
                'handyman_id' => 35,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The worker\'s engine diagnostics were accurate and efficient, keeping my vehicle in top shape. 😌',
                'created_at' => '2023-10-02 07:05:46',
                'updated_at' => '2023-10-02 09:54:34',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'booking_id' => 144,
                'service_id' => 41,
                'handyman_id' => 25,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The tailor\'s patchwork and fabric repair skills were commendable, restoring our clothes beautifully. 🥰🤩',
                'created_at' => '2023-10-02 07:11:59',
                'updated_at' => '2023-10-02 07:11:59',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'booking_id' => 145,
                'service_id' => 58,
                'handyman_id' => 36,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Efficient smart appliance integration service, making our home smarter and more convenient. 😍',
                'created_at' => '2023-10-02 07:30:29',
                'updated_at' => '2023-10-02 07:30:29',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'booking_id' => 146,
                'service_id' => 67,
                'handyman_id' => 18,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Thorough and efficient office sanitization. A job well done to ensure a clean and safe workspace.🤩',
                'created_at' => '2023-10-02 07:38:46',
                'updated_at' => '2023-10-02 07:38:46',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'booking_id' => 147,
                'service_id' => 78,
                'handyman_id' => 32,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Highly satisfied with the artistic touch on my nails 💅🏻 Your work speaks volumes! 🤩',
                'created_at' => '2023-10-02 07:45:38',
                'updated_at' => '2023-10-02 07:45:57',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'booking_id' => 148,
                'service_id' => 60,
                'handyman_id' => 34,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Efficient clogged drain cleaning that resolved the issue promptly. Thanks for the quick response! 🥰',
                'created_at' => '2023-10-02 09:38:13',
                'updated_at' => '2023-10-02 09:38:13',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'booking_id' => 149,
                'service_id' => 77,
                'handyman_id' => 18,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'The murals and wall art 🖌️👨‍🎨 created a captivating ambiance. Their artistic talent transformed our space beautifully. 👩‍🎨',
                'created_at' => '2023-10-02 09:47:38',
                'updated_at' => '2023-10-02 09:48:03',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'booking_id' => 150,
                'service_id' => 48,
                'handyman_id' => 35,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Efficient and convenient clothing wash and fold service. Appreciate the consistent quality. 👚👕👔',
                'created_at' => '2023-10-02 09:53:52',
                'updated_at' => '2023-10-02 09:53:52',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'booking_id' => 151,
                'service_id' => 29,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The indoor lighting 🏮💡 installation was carried out with precision and care, brightening up our space beautifully. 🥰',
                'created_at' => '2023-10-02 10:02:07',
                'updated_at' => '2023-10-02 10:02:07',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'booking_id' => 152,
                'service_id' => 25,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'The authentic Mexican chef\'s 🧑‍🍳culinary skills brought a delightful fiesta to our table. A flavorful experience we\'ll cherish. 🌯🌮',
                'created_at' => '2023-10-02 10:12:08',
                'updated_at' => '2023-10-02 10:12:08',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'booking_id' => 153,
                'service_id' => 20,
                'handyman_id' => 36,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Thorough carpet cleaning 🧹🧼🧽 that brought life back to our carpets. We appreciate the dedication to cleanliness. 🥰',
                'created_at' => '2023-10-02 10:19:57',
                'updated_at' => '2023-10-02 10:20:28',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'booking_id' => 154,
                'service_id' => 14,
                'handyman_id' => 21,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Efficient tire rotation and balancing 🚙 service that ensured a smoother ride. Thank you for your thorough work. 🥰',
                'created_at' => '2023-10-02 10:31:51',
                'updated_at' => '2023-10-02 10:31:51',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'booking_id' => 155,
                'service_id' => 36,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Efficient AC tune-up service that kept my system running smoothly. 🛠️🪛',
                'created_at' => '2023-10-02 10:48:30',
                'updated_at' => '2023-10-02 10:48:30',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'booking_id' => 156,
                'service_id' => 12,
                'handyman_id' => 22,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Skilled and prompt window AC installation, ensuring comfort in no time. 🛠️🪛',
                'created_at' => '2023-10-02 11:40:15',
                'updated_at' => '2023-10-02 11:40:15',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'booking_id' => 157,
                'service_id' => 13,
                'handyman_id' => 23,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Efficient oil change and thorough fluid checks, maintaining my vehicle\'s health. 🥰🛠️',
                'created_at' => '2023-10-02 11:49:43',
                'updated_at' => '2023-10-02 11:49:43',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'booking_id' => 158,
                'service_id' => 19,
                'handyman_id' => 25,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Efficient cleaning service, greatly appreciated for refreshing our ceilings and walls.🧹🧼🧽',
                'created_at' => '2023-10-02 11:55:25',
                'updated_at' => '2023-10-02 11:55:25',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'booking_id' => 159,
                'service_id' => 24,
                'handyman_id' => 27,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Flavorsome family-style dinners, crafted with care and creativity. 🍜🥪🌯🍲',
                'created_at' => '2023-10-02 12:05:27',
                'updated_at' => '2023-10-02 12:05:27',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'booking_id' => 160,
                'service_id' => 28,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Efficient wiring repair, ensuring our electrical issues were resolved. 🛠️🪛',
                'created_at' => '2023-10-02 12:12:09',
                'updated_at' => '2023-10-02 12:12:09',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'booking_id' => 161,
                'service_id' => 61,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Meticulous hair coloring, my new look is perfect! 🥰🤩',
                'created_at' => '2023-10-02 12:19:52',
                'updated_at' => '2023-10-02 12:19:52',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'booking_id' => 162,
                'service_id' => 75,
                'handyman_id' => 25,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Efficient whole-house exterior painting, breathing new life into our property. 😊',
                'created_at' => '2023-10-02 12:26:46',
                'updated_at' => '2023-10-02 12:26:46',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'booking_id' => 164,
                'service_id' => 53,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Efficient pipe bursting repair, saved us from a plumbing disaster. 😍🪛🛠️',
                'created_at' => '2023-10-02 12:35:01',
                'updated_at' => '2023-10-02 12:35:01',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'booking_id' => 165,
                'service_id' => 64,
                'handyman_id' => 36,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Efficient color touch-ups and maintenance, renewing our space effortlessly. 😊😍',
                'created_at' => '2023-10-02 12:40:13',
                'updated_at' => '2023-10-02 12:40:13',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'booking_id' => 166,
                'service_id' => 54,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Thorough high-touch point disinfection – thank you for your dedication to safety. 🤩😍',
                'created_at' => '2023-10-02 12:46:18',
                'updated_at' => '2023-10-02 12:46:18',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'booking_id' => 167,
                'service_id' => 56,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Efficient smart lighting installation, elevating our home\'s ambiance. 🏮💡🤩',
                'created_at' => '2023-10-02 12:50:24',
                'updated_at' => '2023-10-02 12:50:24',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'booking_id' => 168,
                'service_id' => 39,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Efficient garment restoration, bringing my clothes back to life. 🥻👘🧥',
                'created_at' => '2023-10-02 13:01:27',
                'updated_at' => '2023-10-02 13:01:27',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'booking_id' => 169,
                'service_id' => 40,
                'handyman_id' => 20,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Efficient home theater setup, transforming our entertainment experience. 🥰',
                'created_at' => '2023-10-02 13:06:20',
                'updated_at' => '2023-10-02 13:06:20',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'booking_id' => 170,
                'service_id' => 45,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Personalized facial treatment, catering to my skin\'s unique needs. 🧖🥰',
                'created_at' => '2023-10-02 13:13:29',
                'updated_at' => '2023-10-02 13:13:29',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'booking_id' => 171,
                'service_id' => 50,
                'handyman_id' => 25,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Efficient whole-room painting, transforming our space beautifully. 🖌️😍',
                'created_at' => '2023-10-02 13:19:55',
                'updated_at' => '2023-10-02 13:19:55',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'booking_id' => 172,
                'service_id' => 23,
                'handyman_id' => 36,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Consistently reliable daily meal preparation, making life easier and tastier. 👩🏻‍🍳🍲🥪',
                'created_at' => '2023-10-02 13:28:18',
                'updated_at' => '2023-10-02 13:28:18',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'booking_id' => 173,
                'service_id' => 18,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Thorough house cleaning, maintaining a clean and organized living environment. 🧼🧽🧹',
                'created_at' => '2023-10-02 13:34:15',
                'updated_at' => '2023-10-02 13:34:15',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'booking_id' => 65,
                'service_id' => 63,
                'handyman_id' => 4,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'Our experience with the worker\'s bed bug removal was thorough and effective. 🥰',
                'created_at' => '2023-10-02 13:37:38',
                'updated_at' => '2023-10-02 13:37:38',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'booking_id' => 60,
                'service_id' => 83,
                'handyman_id' => 4,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Outstanding attention to detail in drainage system pest management! The service was thorough and efficient, leaving us pest-free. 😊',
                'created_at' => '2023-10-02 13:39:08',
                'updated_at' => '2023-10-02 13:39:08',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'booking_id' => 58,
                'service_id' => 78,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 5.0,
                'review' => 'You\'ve got a real talent for nail artistry. My nails look fantastic, thanks to your skills. 💅😍',
                'created_at' => '2023-10-02 13:40:21',
                'updated_at' => '2023-10-02 13:40:21',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'booking_id' => 57,
                'service_id' => 72,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Our dining area was thoroughly cleaned, ensuring a safe experience.  🤩😍',
                'created_at' => '2023-10-02 13:41:18',
                'updated_at' => '2023-10-02 13:41:18',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'booking_id' => 55,
                'service_id' => 96,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Outstanding nail care service! The worker was skilled, and my hands and feet have never looked better. Definitely deserving of a 4-star review.  😍💅',
                'created_at' => '2023-10-02 13:43:28',
                'updated_at' => '2023-10-02 13:43:28',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'booking_id' => 178,
                'service_id' => 104,
                'handyman_id' => 51,
                'customer_id' => 50,
                'rating' => 4.0,
                'review' => 'Our custom clothing needs were met with skill and meticulous craftsmanship. 🪡🌞',
                'created_at' => '2023-10-03 12:21:00',
                'updated_at' => '2023-10-03 12:21:00',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'booking_id' => 179,
                'service_id' => 110,
                'handyman_id' => 36,
                'customer_id' => 50,
                'rating' => 4.0,
                'review' => 'Outstanding filter replacement! The technician\'s expertise and attention to detail were impressive.   🥰',
                'created_at' => '2023-10-03 12:25:22',
                'updated_at' => '2023-10-03 12:25:22',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'booking_id' => 180,
                'service_id' => 100,
                'handyman_id' => 51,
                'customer_id' => 49,
                'rating' => 4.0,
                'review' => 'Outstanding attention to detail in frame design! The work reflects true artistry and dedication. Exceptional service! 🥰🖌️',
                'created_at' => '2023-10-03 12:35:02',
                'updated_at' => '2023-10-03 12:35:02',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'booking_id' => 181,
                'service_id' => 110,
                'handyman_id' => 51,
                'customer_id' => 48,
                'rating' => 4.0,
                'review' => 'Impressed by the skill and dedication in filter replacement. 🪛🛠️',
                'created_at' => '2023-10-03 12:41:16',
                'updated_at' => '2023-10-03 12:41:16',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'booking_id' => 182,
                'service_id' => 107,
                'handyman_id' => 51,
                'customer_id' => 48,
                'rating' => 5.0,
                'review' => 'Outstanding attention to detail in office cleaning! 🧽🧼 The cleaner\'s efficiency and reliability were impressive. Definitely deserving of a 5-star review. 🧹',
                'created_at' => '2023-10-03 13:08:30',
                'updated_at' => '2023-10-03 13:08:38',
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'booking_id' => 183,
                'service_id' => 104,
                'handyman_id' => 51,
                'customer_id' => 47,
                'rating' => 4.0,
                'review' => 'Effective seam repair and reinforcement service - our garments feel renewed. 🥰🧵',
                'created_at' => '2023-10-03 13:12:31',
                'updated_at' => '2023-10-03 13:12:31',
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'booking_id' => 184,
                'service_id' => 107,
                'handyman_id' => 51,
                'customer_id' => 46,
                'rating' => 5.0,
                'review' => 'Impressed by the dedication and thoroughness in office cleaning service. 🧹🧼',
                'created_at' => '2023-10-03 13:17:42',
                'updated_at' => '2023-10-03 13:17:42',
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'booking_id' => 186,
                'service_id' => 110,
                'handyman_id' => 51,
                'customer_id' => 41,
                'rating' => 5.0,
                'review' => 'Flawless filter replacement service! The quality of work and improved system performance are exceptional, earning them a solid 5 stars. 😘🌞',
                'created_at' => '2023-10-05 06:03:47',
                'updated_at' => '2023-10-05 06:03:47',
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'booking_id' => 187,
                'service_id' => 100,
                'handyman_id' => 51,
                'customer_id' => 40,
                'rating' => 4.0,
                'review' => 'Top-notch frame design service! My artwork has found the perfect complement. Outstanding job! 🖼️🌅',
                'created_at' => '2023-10-05 06:10:15',
                'updated_at' => '2023-10-05 06:10:15',
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'booking_id' => 188,
                'service_id' => 104,
                'handyman_id' => 51,
                'customer_id' => 39,
                'rating' => 5.0,
                'review' => 'The service improved the durability of our clothing 👕🥻 through precise seam repair and reinforcement.',
                'created_at' => '2023-10-05 06:16:03',
                'updated_at' => '2023-10-05 06:42:01',
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'booking_id' => 189,
                'service_id' => 110,
                'handyman_id' => 51,
                'customer_id' => 39,
                'rating' => 5.0,
                'review' => 'Reliable and top-notch filter replacement. Our home feels fresher already. Happy to give them a well-earned 5-star review! 🥰😍',
                'created_at' => '2023-10-05 06:19:59',
                'updated_at' => '2023-10-05 06:19:59',
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'booking_id' => 190,
                'service_id' => 110,
                'handyman_id' => 51,
                'customer_id' => 38,
                'rating' => 5.0,
                'review' => 'Smooth AC filter replacement, ensuring our home stays comfortable.🪛😍',
                'created_at' => '2023-10-05 06:37:43',
                'updated_at' => '2023-10-05 06:37:43',
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'booking_id' => 191,
                'service_id' => 104,
                'handyman_id' => 51,
                'customer_id' => 38,
                'rating' => 4.0,
                'review' => 'Clothing repairs were handled with expertise, ensuring long-lasting wear. 🥻👕👔👖',
                'created_at' => '2023-10-05 06:39:30',
                'updated_at' => '2023-10-05 06:39:30',
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'booking_id' => 193,
                'service_id' => 107,
                'handyman_id' => 51,
                'customer_id' => 37,
                'rating' => 4.0,
                'review' => 'Flawless office cleaning! The quality of work and cleanliness are exceptional, earning them a solid 4 stars. 🧹🧼🌞',
                'created_at' => '2023-10-05 06:51:50',
                'updated_at' => '2023-10-05 06:51:50',
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'booking_id' => 194,
                'service_id' => 97,
                'handyman_id' => 51,
                'customer_id' => 48,
                'rating' => 5.0,
                'review' => 'Outstanding compressor repair! The technician\'s expertise and efficiency were impressive. Definitely deserving of a 5-star review. 🛠️🪛😍',
                'created_at' => '2023-10-05 07:11:25',
                'updated_at' => '2023-10-05 07:11:25',
                'deleted_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'booking_id' => 195,
                'service_id' => 26,
                'handyman_id' => 51,
                'customer_id' => 3,
                'rating' => 4.0,
                'review' => 'Our meal was a delicious journey to China, thanks to the chef\'s culinary skills. 😍🍜🍝',
                'created_at' => '2023-10-05 07:21:22',
                'updated_at' => '2023-10-05 07:21:22',
                'deleted_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'booking_id' => 197,
                'service_id' => 81,
                'handyman_id' => 51,
                'customer_id' => 50,
                'rating' => 4.0,
                'review' => 'Our space now reflects the painter\'s skill and vision, making it truly unique. 🖼️🌅',
                'created_at' => '2023-10-05 07:30:09',
                'updated_at' => '2023-10-05 07:30:09',
                'deleted_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'booking_id' => 199,
                'service_id' => 15,
                'handyman_id' => 51,
                'customer_id' => 49,
                'rating' => 4.0,
                'review' => 'Our chairs have been expertly revived, thanks to the carpenter\'s skill and care. 🪑🪚',
                'created_at' => '2023-10-05 07:37:49',
                'updated_at' => '2023-10-05 07:37:49',
                'deleted_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'booking_id' => 201,
                'service_id' => 105,
                'handyman_id' => 51,
                'customer_id' => 47,
                'rating' => 4.0,
                'review' => 'Outstanding attention to detail in custom cake design! 🧁🍰🎂 The chef\'s creativity and flavors left us in awe. 🥰🌞',
                'created_at' => '2023-10-05 08:13:53',
                'updated_at' => '2023-10-05 08:14:32',
                'deleted_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'booking_id' => 202,
                'service_id' => 35,
                'handyman_id' => 51,
                'customer_id' => 43,
                'rating' => 4.0,
                'review' => 'Professional service, ensuring our home is spotless and hygienic with expertise.  🥰🌞',
                'created_at' => '2023-10-05 08:22:12',
                'updated_at' => '2023-10-05 08:23:16',
                'deleted_at' => '2023-10-05 08:23:16',
            ),
            126 => 
            array (
                'id' => 127,
                'booking_id' => 203,
                'service_id' => 80,
                'handyman_id' => 51,
                'customer_id' => 46,
                'rating' => 4.0,
                'review' => 'Effective garment cleaning, ensuring our attire looks pristine. 👗👔👕👖',
                'created_at' => '2023-10-05 09:51:41',
                'updated_at' => '2023-10-05 09:51:41',
                'deleted_at' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'booking_id' => 207,
                'service_id' => 94,
                'handyman_id' => 51,
                'customer_id' => 44,
                'rating' => 4.0,
                'review' => 'The haircut and styling service met my expectations, enhancing my look. 💇🏻‍♀️😍',
                'created_at' => '2023-10-05 10:08:56',
                'updated_at' => '2023-10-05 10:08:56',
                'deleted_at' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'booking_id' => 208,
                'service_id' => 110,
                'handyman_id' => 51,
                'customer_id' => 45,
                'rating' => 5.0,
                'review' => 'Expert service, optimizing our AC unit for peak performance. 🪛🛠️🥰',
                'created_at' => '2023-10-05 10:13:25',
                'updated_at' => '2023-10-05 10:13:25',
                'deleted_at' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'booking_id' => 209,
                'service_id' => 101,
                'handyman_id' => 51,
                'customer_id' => 42,
                'rating' => 5.0,
                'review' => 'Our leaks were skillfully addressed, leaving our home dry and secure. ☺️🤩',
                'created_at' => '2023-10-05 10:17:42',
                'updated_at' => '2023-10-05 10:18:54',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}