<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PaymentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('payments')->delete();
        
        \DB::table('payments')->insert(array (
            0 => 
            array (
                'booking_id' => 6,
                'created_at' => '2023-09-05 09:55:38',
                'customer_id' => 42,
                'datetime' => '2023-09-05 15:25:39',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 1,
                'other_transaction_detail' => NULL,
                'payment_status' => 'advanced_paid',
                'payment_type' => 'stripe',
                'total_amount' => 2.367,
                'txn_id' => 'pi_1NmvyiFTMa5P8ht05u2GQ2Dm',
                'updated_at' => '2023-09-05 09:55:38',
            ),
            1 => 
            array (
                'booking_id' => 6,
                'created_at' => '2023-09-05 10:10:32',
                'customer_id' => 42,
                'datetime' => '2023-09-05 15:40:33',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 2,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 31.803,
                'txn_id' => 'pi_1NmwD8FTMa5P8ht0g3FjloV6',
                'updated_at' => '2023-09-05 10:10:32',
            ),
            2 => 
            array (
                'booking_id' => 2,
                'created_at' => '2023-09-05 10:27:26',
                'customer_id' => 41,
                'datetime' => '2023-09-05 15:57:26',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 3,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'cash',
                'total_amount' => 101.1,
                'txn_id' => '#2',
                'updated_at' => '2023-09-05 02:35:25',
            ),
            3 => 
            array (
                'booking_id' => 7,
                'created_at' => '2023-09-05 10:37:43',
                'customer_id' => 41,
                'datetime' => '2023-09-05 16:07:44',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 4,
                'other_transaction_detail' => NULL,
                'payment_status' => 'advanced_paid',
                'payment_type' => 'stripe',
                'total_amount' => 2.367,
                'txn_id' => 'pi_1NmwdQFTMa5P8ht02TgikHRD',
                'updated_at' => '2023-09-05 10:37:43',
            ),
            4 => 
            array (
                'booking_id' => 10,
                'created_at' => '2023-09-05 10:52:04',
                'customer_id' => 43,
                'datetime' => '2023-09-05 16:22:05',
                'deleted_at' => '2023-09-12 08:09:48',
                'discount' => 2.0,
                'id' => 5,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 29.73,
                'txn_id' => '#10',
                'updated_at' => '2023-09-12 08:09:48',
            ),
            5 => 
            array (
                'booking_id' => 24,
                'created_at' => '2023-09-09 08:09:03',
                'customer_id' => 3,
                'datetime' => '2023-09-09 13:39:02',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 6,
                'other_transaction_detail' => NULL,
                'payment_status' => 'advanced_paid',
                'payment_type' => 'stripe',
                'total_amount' => 4.81,
                'txn_id' => 'pi_1NoMDjFTMa5P8ht0mdfnG13A',
                'updated_at' => '2023-09-09 08:09:03',
            ),
            6 => 
            array (
                'booking_id' => 31,
                'created_at' => '2023-09-09 13:17:43',
                'customer_id' => 3,
                'datetime' => '2023-09-09 18:47:42',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 7,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 27.1,
                'txn_id' => '#31',
                'updated_at' => '2023-09-09 13:17:43',
            ),
            7 => 
            array (
                'booking_id' => 35,
                'created_at' => '2023-09-12 06:38:05',
                'customer_id' => 3,
                'datetime' => '2023-09-12 12:08:05',
                'deleted_at' => NULL,
                'discount' => 1.0,
                'id' => 8,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 24.74,
                'txn_id' => '#35',
                'updated_at' => '2023-09-12 06:38:05',
            ),
            8 => 
            array (
                'booking_id' => 39,
                'created_at' => '2023-09-12 07:29:54',
                'customer_id' => 3,
                'datetime' => '2023-09-12 12:59:53',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 9,
                'other_transaction_detail' => NULL,
                'payment_status' => 'advanced_paid',
                'payment_type' => 'wallet',
                'total_amount' => 0.752,
                'txn_id' => '#39',
                'updated_at' => '2023-09-12 07:29:54',
            ),
            9 => 
            array (
                'booking_id' => 40,
                'created_at' => '2023-09-12 07:37:34',
                'customer_id' => 3,
                'datetime' => '2023-09-12 13:07:34',
                'deleted_at' => '2023-09-12 08:09:48',
                'discount' => 0.0,
                'id' => 10,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 19.75,
                'txn_id' => '#40',
                'updated_at' => '2023-09-12 08:09:48',
            ),
            10 => 
            array (
                'booking_id' => 41,
                'created_at' => '2023-09-12 08:04:24',
                'customer_id' => 3,
                'datetime' => '2023-09-12 13:34:23',
                'deleted_at' => NULL,
                'discount' => 5.0,
                'id' => 11,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'cash',
                'total_amount' => 31.34,
                'txn_id' => '#41',
                'updated_at' => '2023-09-20 16:22:22',
            ),
            11 => 
            array (
                'booking_id' => 43,
                'created_at' => '2023-09-12 09:30:13',
                'customer_id' => 3,
                'datetime' => '2023-09-12 15:00:12',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 12,
                'other_transaction_detail' => NULL,
                'payment_status' => 'advanced_paid',
                'payment_type' => 'stripe',
                'total_amount' => 0.752,
                'txn_id' => 'pi_1NpStzFTMa5P8ht0LYiTv25e',
                'updated_at' => '2023-09-12 09:30:13',
            ),
            12 => 
            array (
                'booking_id' => 49,
                'created_at' => '2023-09-19 06:47:04',
                'customer_id' => 3,
                'datetime' => '2023-09-19 12:17:02',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 13,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 23.6,
                'txn_id' => 'pi_1NrxhnFTMa5P8ht0NThSV4zD',
                'updated_at' => '2023-09-19 06:47:04',
            ),
            13 => 
            array (
                'booking_id' => 50,
                'created_at' => '2023-09-19 06:58:14',
                'customer_id' => 3,
                'datetime' => '2023-09-19 12:28:13',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 14,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 46.0,
                'txn_id' => '#50',
                'updated_at' => '2023-09-19 06:58:14',
            ),
            14 => 
            array (
                'booking_id' => 53,
                'created_at' => '2023-09-20 06:47:14',
                'customer_id' => 3,
                'datetime' => '2023-09-20 12:17:13',
                'deleted_at' => NULL,
                'discount' => 5.0,
                'id' => 16,
                'other_transaction_detail' => NULL,
                'payment_status' => 'advanced_paid',
                'payment_type' => 'stripe',
                'total_amount' => 2.1068,
                'txn_id' => 'pi_1NsKBOFTMa5P8ht0WvUYKIOC',
                'updated_at' => '2023-09-20 06:47:14',
            ),
            15 => 
            array (
                'booking_id' => 54,
                'created_at' => '2023-09-20 06:53:05',
                'customer_id' => 3,
                'datetime' => '2023-09-20 12:23:04',
                'deleted_at' => NULL,
                'discount' => 1.0,
                'id' => 17,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 12.27,
                'txn_id' => '#54',
                'updated_at' => '2023-09-20 06:53:18',
            ),
            16 => 
            array (
                'booking_id' => 55,
                'created_at' => '2023-09-20 07:02:41',
                'customer_id' => 3,
                'datetime' => '2023-09-20 12:32:40',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 18,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 30.75,
                'txn_id' => '#55',
                'updated_at' => '2023-09-20 07:04:33',
            ),
            17 => 
            array (
                'booking_id' => 57,
                'created_at' => '2023-09-20 07:16:55',
                'customer_id' => 3,
                'datetime' => '2023-09-20 12:46:54',
                'deleted_at' => NULL,
                'discount' => 10.0,
                'id' => 19,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 51.25,
                'txn_id' => '#57',
                'updated_at' => '2023-09-20 07:17:25',
            ),
            18 => 
            array (
                'booking_id' => 58,
                'created_at' => '2023-09-20 10:22:32',
                'customer_id' => 3,
                'datetime' => '2023-09-20 15:52:32',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 20,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending',
                'payment_type' => 'cash',
                'total_amount' => 52.57,
                'txn_id' => '#58',
                'updated_at' => '2023-09-20 10:22:32',
            ),
            19 => 
            array (
                'booking_id' => 60,
                'created_at' => '2023-09-27 06:19:12',
                'customer_id' => 3,
                'datetime' => '2023-09-27 11:49:10',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 21,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 46.34,
                'txn_id' => '#60',
                'updated_at' => '2023-09-27 06:19:12',
            ),
            20 => 
            array (
                'booking_id' => 61,
                'created_at' => '2023-09-27 07:02:07',
                'customer_id' => 3,
                'datetime' => '2023-09-27 12:32:04',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 22,
                'other_transaction_detail' => NULL,
                'payment_status' => 'advanced_paid',
                'payment_type' => 'stripe',
                'total_amount' => 4.678,
                'txn_id' => 'pi_1NurkaFTMa5P8ht0jodPRyZ4',
                'updated_at' => '2023-09-27 07:02:07',
            ),
            21 => 
            array (
                'booking_id' => 65,
                'created_at' => '2023-09-27 10:40:51',
                'customer_id' => 3,
                'datetime' => '2023-09-27 16:10:48',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 23,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 54.4,
                'txn_id' => '#65',
                'updated_at' => '2023-09-27 11:39:43',
            ),
            22 => 
            array (
                'booking_id' => 66,
                'created_at' => '2023-09-27 11:47:16',
                'customer_id' => 3,
                'datetime' => '2023-09-27 17:17:14',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 24,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 48.1,
                'txn_id' => '#66',
                'updated_at' => '2023-09-27 11:47:27',
            ),
            23 => 
            array (
                'booking_id' => 67,
                'created_at' => '2023-09-27 11:51:02',
                'customer_id' => 3,
                'datetime' => '2023-09-27 17:20:59',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 25,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 26.25,
                'txn_id' => 'pi_1NuwGNFTMa5P8ht0aacDTglS',
                'updated_at' => '2023-09-27 11:51:02',
            ),
            24 => 
            array (
                'booking_id' => 68,
                'created_at' => '2023-09-27 11:53:50',
                'customer_id' => 3,
                'datetime' => '2023-09-27 17:23:47',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 26,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 47.22,
                'txn_id' => '#68',
                'updated_at' => '2023-09-27 11:54:12',
            ),
            25 => 
            array (
                'booking_id' => 69,
                'created_at' => '2023-09-27 12:02:51',
                'customer_id' => 3,
                'datetime' => '2023-09-27 17:32:49',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 27,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 73.3,
                'txn_id' => '#69',
                'updated_at' => '2023-09-27 12:03:13',
            ),
            26 => 
            array (
                'booking_id' => 70,
                'created_at' => '2023-09-27 12:06:40',
                'customer_id' => 3,
                'datetime' => '2023-09-27 17:36:38',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 28,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 30.25,
                'txn_id' => 'pi_1NuwVRFTMa5P8ht0PXgQxNRw',
                'updated_at' => '2023-09-27 12:06:40',
            ),
            27 => 
            array (
                'booking_id' => 71,
                'created_at' => '2023-09-27 12:11:26',
                'customer_id' => 3,
                'datetime' => '2023-09-27 17:41:24',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 29,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 18.52,
                'txn_id' => '#71',
                'updated_at' => '2023-09-27 12:12:09',
            ),
            28 => 
            array (
                'booking_id' => 72,
                'created_at' => '2023-09-27 12:30:06',
                'customer_id' => 3,
                'datetime' => '2023-09-27 18:00:04',
                'deleted_at' => NULL,
                'discount' => 5.0,
                'id' => 30,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 65.4,
                'txn_id' => '#72',
                'updated_at' => '2023-09-27 12:30:06',
            ),
            29 => 
            array (
                'booking_id' => 73,
                'created_at' => '2023-09-27 12:33:39',
                'customer_id' => 3,
                'datetime' => '2023-09-27 18:03:37',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 31,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 46.34,
                'txn_id' => 'pi_1NuwvbFTMa5P8ht0ayZ3aqHY',
                'updated_at' => '2023-09-27 12:33:39',
            ),
            30 => 
            array (
                'booking_id' => 74,
                'created_at' => '2023-09-27 12:41:48',
                'customer_id' => 3,
                'datetime' => '2023-09-27 18:11:46',
                'deleted_at' => NULL,
                'discount' => 4.0,
                'id' => 32,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending',
                'payment_type' => 'cash',
                'total_amount' => 40.29,
                'txn_id' => '#74',
                'updated_at' => '2023-09-27 12:41:48',
            ),
            31 => 
            array (
                'booking_id' => 75,
                'created_at' => '2023-09-29 05:45:58',
                'customer_id' => 3,
                'datetime' => '2023-09-29 11:15:57',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 33,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 39.7,
                'txn_id' => '#75',
                'updated_at' => '2023-09-29 05:45:58',
            ),
            32 => 
            array (
                'booking_id' => 77,
                'created_at' => '2023-09-29 05:50:42',
                'customer_id' => 3,
                'datetime' => '2023-09-29 11:20:40',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 34,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 20.16,
                'txn_id' => '#77',
                'updated_at' => '2023-09-29 05:50:42',
            ),
            33 => 
            array (
                'booking_id' => 78,
                'created_at' => '2023-09-29 06:21:21',
                'customer_id' => 3,
                'datetime' => '2023-09-29 11:51:20',
                'deleted_at' => NULL,
                'discount' => 5.0,
                'id' => 35,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending',
                'payment_type' => 'cash',
                'total_amount' => 31.93,
                'txn_id' => '#78',
                'updated_at' => '2023-09-29 06:21:21',
            ),
            34 => 
            array (
                'booking_id' => 78,
                'created_at' => '2023-09-29 06:21:22',
                'customer_id' => 3,
                'datetime' => '2023-09-29 11:51:20',
                'deleted_at' => NULL,
                'discount' => 5.0,
                'id' => 36,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending',
                'payment_type' => 'cash',
                'total_amount' => 31.93,
                'txn_id' => '#78',
                'updated_at' => '2023-09-29 06:21:22',
            ),
            35 => 
            array (
                'booking_id' => 79,
                'created_at' => '2023-09-29 06:24:55',
                'customer_id' => 3,
                'datetime' => '2023-09-29 11:54:53',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 37,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 23.6,
                'txn_id' => '#79',
                'updated_at' => '2023-09-29 06:25:09',
            ),
            36 => 
            array (
                'booking_id' => 80,
                'created_at' => '2023-09-29 06:29:45',
                'customer_id' => 3,
                'datetime' => '2023-09-29 11:59:44',
                'deleted_at' => NULL,
                'discount' => 4.0,
                'id' => 38,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 36.13,
                'txn_id' => 'pi_1NvaCaFTMa5P8ht0jXsMCHMs',
                'updated_at' => '2023-09-29 06:29:45',
            ),
            37 => 
            array (
                'booking_id' => 84,
                'created_at' => '2023-09-29 07:00:18',
                'customer_id' => 3,
                'datetime' => '2023-09-29 12:30:16',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 45,
                'other_transaction_detail' => NULL,
                'payment_status' => 'advanced_paid',
                'payment_type' => 'stripe',
                'total_amount' => 0.752,
                'txn_id' => 'pi_1Nvag2FTMa5P8ht0utNtVMBm',
                'updated_at' => '2023-09-29 07:00:18',
            ),
            38 => 
            array (
                'booking_id' => 84,
                'created_at' => '2023-09-29 07:02:31',
                'customer_id' => 3,
                'datetime' => '2023-09-29 12:32:30',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 46,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 36.848,
                'txn_id' => '#84',
                'updated_at' => '2023-09-29 07:02:31',
            ),
            39 => 
            array (
                'booking_id' => 85,
                'created_at' => '2023-09-29 07:29:49',
                'customer_id' => 3,
                'datetime' => '2023-09-29 12:59:48',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 47,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 31.3,
                'txn_id' => '#85',
                'updated_at' => '2023-09-29 07:29:49',
            ),
            40 => 
            array (
                'booking_id' => 86,
                'created_at' => '2023-09-29 07:36:32',
                'customer_id' => 3,
                'datetime' => '2023-09-29 13:06:31',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 49,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 47.05,
                'txn_id' => '#86',
                'updated_at' => '2023-09-29 07:36:32',
            ),
            41 => 
            array (
                'booking_id' => 87,
                'created_at' => '2023-09-29 07:40:27',
                'customer_id' => 3,
                'datetime' => '2023-09-29 13:10:26',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 52,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 16.6,
                'txn_id' => '#87',
                'updated_at' => '2023-09-29 07:40:42',
            ),
            42 => 
            array (
                'booking_id' => 88,
                'created_at' => '2023-09-29 07:44:08',
                'customer_id' => 3,
                'datetime' => '2023-09-29 13:14:07',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 54,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 41.8,
                'txn_id' => 'pi_1NvbMXFTMa5P8ht040Dpkdb8',
                'updated_at' => '2023-09-29 07:44:08',
            ),
            43 => 
            array (
                'booking_id' => 89,
                'created_at' => '2023-09-29 07:46:49',
                'customer_id' => 3,
                'datetime' => '2023-09-29 07:46:49',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 56,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 32.0,
                'txn_id' => NULL,
                'updated_at' => '2023-09-29 13:19:02',
            ),
            44 => 
            array (
                'booking_id' => 89,
                'created_at' => '2023-09-29 07:47:22',
                'customer_id' => 3,
                'datetime' => '2023-09-29 07:47:22',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 57,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 43.0,
                'txn_id' => NULL,
                'updated_at' => '2023-09-29 07:47:22',
            ),
            45 => 
            array (
                'booking_id' => 90,
                'created_at' => '2023-09-29 07:51:57',
                'customer_id' => 3,
                'datetime' => '2023-09-29 13:21:55',
                'deleted_at' => NULL,
                'discount' => NULL,
                'id' => 58,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 21.85,
                'txn_id' => 'pi_1NvbU6FTMa5P8ht0jSmSI92D',
                'updated_at' => '2023-09-29 07:51:57',
            ),
            46 => 
            array (
                'booking_id' => 91,
                'created_at' => '2023-09-29 07:58:23',
                'customer_id' => 3,
                'datetime' => '2023-09-29 13:28:22',
                'deleted_at' => NULL,
                'discount' => 4.0,
                'id' => 59,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 42.3,
                'txn_id' => 'pi_1NvbaLFTMa5P8ht06V2rzwxf',
                'updated_at' => '2023-09-29 07:58:23',
            ),
            47 => 
            array (
                'booking_id' => 92,
                'created_at' => '2023-09-29 08:00:49',
                'customer_id' => 3,
                'datetime' => '2023-09-29 13:30:47',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 60,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 19.28,
                'txn_id' => '#92',
                'updated_at' => '2023-09-29 08:00:49',
            ),
            48 => 
            array (
                'booking_id' => 93,
                'created_at' => '2023-09-29 08:08:46',
                'customer_id' => 3,
                'datetime' => '2023-09-29 13:38:45',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 61,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 19.75,
                'txn_id' => '#93',
                'updated_at' => '2023-09-29 08:08:59',
            ),
            49 => 
            array (
                'booking_id' => 94,
                'created_at' => '2023-09-29 08:12:24',
                'customer_id' => 3,
                'datetime' => '2023-09-29 13:42:23',
                'deleted_at' => NULL,
                'discount' => 1.0,
                'id' => 62,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'cash',
                'total_amount' => 46.62,
                'txn_id' => '#94',
                'updated_at' => '2023-09-29 13:48:43',
            ),
            50 => 
            array (
                'booking_id' => 1,
                'created_at' => '2023-09-29 08:14:14',
                'customer_id' => 3,
                'datetime' => '2023-09-29 08:14:14',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 63,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 29.99,
                'txn_id' => NULL,
                'updated_at' => '2023-09-29 08:14:14',
            ),
            51 => 
            array (
                'booking_id' => 95,
                'created_at' => '2023-09-29 08:16:52',
                'customer_id' => 3,
                'datetime' => '2023-09-29 13:46:50',
                'deleted_at' => NULL,
                'discount' => 7.0,
                'id' => 64,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'cash',
                'total_amount' => 30.75,
                'txn_id' => '#95',
                'updated_at' => '2023-09-29 13:48:32',
            ),
            52 => 
            array (
                'booking_id' => 96,
                'created_at' => '2023-09-29 08:25:08',
                'customer_id' => 3,
                'datetime' => '2023-09-29 13:55:07',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 65,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 30.21,
                'txn_id' => 'pi_1Nvc0HFTMa5P8ht09TgZtcaH',
                'updated_at' => '2023-09-29 08:25:08',
            ),
            53 => 
            array (
                'booking_id' => 97,
                'created_at' => '2023-09-29 08:27:54',
                'customer_id' => 3,
                'datetime' => '2023-09-29 13:57:53',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 66,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 15.55,
                'txn_id' => '#97',
                'updated_at' => '2023-09-29 08:28:18',
            ),
            54 => 
            array (
                'booking_id' => 98,
                'created_at' => '2023-09-29 08:34:10',
                'customer_id' => 3,
                'datetime' => '2023-09-29 14:04:08',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 67,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 37.0,
                'txn_id' => '#98',
                'updated_at' => '2023-09-29 08:34:28',
            ),
            55 => 
            array (
                'booking_id' => 99,
                'created_at' => '2023-09-29 09:09:50',
                'customer_id' => 3,
                'datetime' => '2023-09-29 14:39:49',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 68,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 13.0,
                'txn_id' => '#99',
                'updated_at' => '2023-09-29 09:09:50',
            ),
            56 => 
            array (
                'booking_id' => 100,
                'created_at' => '2023-09-29 09:15:11',
                'customer_id' => 3,
                'datetime' => '2023-09-29 14:45:10',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 69,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 18.52,
                'txn_id' => '#100',
                'updated_at' => '2023-09-29 09:15:24',
            ),
            57 => 
            array (
                'booking_id' => 101,
                'created_at' => '2023-09-29 09:21:22',
                'customer_id' => 3,
                'datetime' => '2023-09-29 14:51:21',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 70,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending',
                'payment_type' => 'cash',
                'total_amount' => 31.3,
                'txn_id' => '#101',
                'updated_at' => '2023-09-29 09:21:22',
            ),
            58 => 
            array (
                'booking_id' => 102,
                'created_at' => '2023-09-29 09:25:55',
                'customer_id' => 3,
                'datetime' => '2023-09-29 14:55:53',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 71,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 19.43,
                'txn_id' => '#102',
                'updated_at' => '2023-09-29 09:25:55',
            ),
            59 => 
            array (
                'booking_id' => 103,
                'created_at' => '2023-09-29 09:31:02',
                'customer_id' => 3,
                'datetime' => '2023-09-29 15:01:01',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 72,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 35.7,
                'txn_id' => '#103',
                'updated_at' => '2023-09-29 09:31:19',
            ),
            60 => 
            array (
                'booking_id' => 104,
                'created_at' => '2023-09-29 09:36:43',
                'customer_id' => 3,
                'datetime' => '2023-09-29 15:06:42',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 73,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 26.05,
                'txn_id' => '#104',
                'updated_at' => '2023-09-29 09:36:43',
            ),
            61 => 
            array (
                'booking_id' => 105,
                'created_at' => '2023-09-29 09:41:03',
                'customer_id' => 3,
                'datetime' => '2023-09-29 15:11:02',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 74,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 23.95,
                'txn_id' => '#105',
                'updated_at' => '2023-09-29 09:41:23',
            ),
            62 => 
            array (
                'booking_id' => 106,
                'created_at' => '2023-09-29 13:14:17',
                'customer_id' => 3,
                'datetime' => '2023-09-29 18:44:16',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 75,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 37.6,
                'txn_id' => '#106',
                'updated_at' => '2023-09-29 13:14:32',
            ),
            63 => 
            array (
                'booking_id' => 108,
                'created_at' => '2023-09-29 13:21:24',
                'customer_id' => 3,
                'datetime' => '2023-09-29 18:51:23',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 76,
                'other_transaction_detail' => NULL,
                'payment_status' => 'advanced_paid',
                'payment_type' => 'stripe',
                'total_amount' => 4.678,
                'txn_id' => 'pi_1NvgczFTMa5P8ht0mivRX10z',
                'updated_at' => '2023-09-29 13:21:24',
            ),
            64 => 
            array (
                'booking_id' => 108,
                'created_at' => '2023-09-29 13:27:41',
                'customer_id' => 3,
                'datetime' => '2023-09-29 18:57:40',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 77,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 42.102,
                'txn_id' => '#108',
                'updated_at' => '2023-09-29 13:27:41',
            ),
            65 => 
            array (
                'booking_id' => 109,
                'created_at' => '2023-09-29 13:37:14',
                'customer_id' => 3,
                'datetime' => '2023-09-29 19:07:12',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 78,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 42.95,
                'txn_id' => '#109',
                'updated_at' => '2023-09-29 13:37:40',
            ),
            66 => 
            array (
                'booking_id' => 110,
                'created_at' => '2023-09-29 13:43:13',
                'customer_id' => 3,
                'datetime' => '2023-09-29 19:13:12',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 79,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 45.76,
                'txn_id' => '#110',
                'updated_at' => '2023-09-29 13:43:13',
            ),
            67 => 
            array (
                'booking_id' => 111,
                'created_at' => '2023-09-30 05:32:28',
                'customer_id' => 3,
                'datetime' => '2023-09-30 11:02:27',
                'deleted_at' => NULL,
                'discount' => 3.0,
                'id' => 80,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 37.91,
                'txn_id' => '#111',
                'updated_at' => '2023-09-30 05:32:28',
            ),
            68 => 
            array (
                'booking_id' => 112,
                'created_at' => '2023-09-30 05:36:46',
                'customer_id' => 3,
                'datetime' => '2023-09-30 11:06:45',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 81,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 39.7,
                'txn_id' => '#112',
                'updated_at' => '2023-09-30 05:36:54',
            ),
            69 => 
            array (
                'booking_id' => 113,
                'created_at' => '2023-09-30 05:47:49',
                'customer_id' => 3,
                'datetime' => '2023-09-30 11:17:47',
                'deleted_at' => NULL,
                'discount' => 3.0,
                'id' => 82,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 30.93,
                'txn_id' => '#113',
                'updated_at' => '2023-09-30 05:48:03',
            ),
            70 => 
            array (
                'booking_id' => 114,
                'created_at' => '2023-09-30 05:50:55',
                'customer_id' => 3,
                'datetime' => '2023-09-30 11:20:53',
                'deleted_at' => NULL,
                'discount' => 4.0,
                'id' => 83,
                'other_transaction_detail' => NULL,
                'payment_status' => 'advanced_paid',
                'payment_type' => 'stripe',
                'total_amount' => 2.6415,
                'txn_id' => 'pi_1Nvw4UFTMa5P8ht0zmhFZFya',
                'updated_at' => '2023-09-30 05:50:55',
            ),
            71 => 
            array (
                'booking_id' => 114,
                'created_at' => '2023-09-30 05:53:07',
                'customer_id' => 3,
                'datetime' => '2023-09-30 11:23:05',
                'deleted_at' => NULL,
                'discount' => 4.0,
                'id' => 84,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 76.4385,
                'txn_id' => '#114',
                'updated_at' => '2023-09-30 05:53:07',
            ),
            72 => 
            array (
                'booking_id' => 115,
                'created_at' => '2023-09-30 06:01:51',
                'customer_id' => 3,
                'datetime' => '2023-09-30 11:31:50',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 85,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 17.65,
                'txn_id' => 'pi_1NvwFAFTMa5P8ht0lIkfEvBo',
                'updated_at' => '2023-09-30 06:01:51',
            ),
            73 => 
            array (
                'booking_id' => 116,
                'created_at' => '2023-09-30 06:08:07',
                'customer_id' => 3,
                'datetime' => '2023-09-30 11:38:05',
                'deleted_at' => NULL,
                'discount' => 3.0,
                'id' => 86,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 48.42,
                'txn_id' => '#116',
                'updated_at' => '2023-09-30 06:08:07',
            ),
            74 => 
            array (
                'booking_id' => 117,
                'created_at' => '2023-09-30 06:14:38',
                'customer_id' => 3,
                'datetime' => '2023-09-30 11:44:37',
                'deleted_at' => NULL,
                'discount' => 4.0,
                'id' => 87,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 41.51,
                'txn_id' => '#117',
                'updated_at' => '2023-09-30 06:14:55',
            ),
            75 => 
            array (
                'booking_id' => 118,
                'created_at' => '2023-09-30 06:25:32',
                'customer_id' => 3,
                'datetime' => '2023-09-30 11:55:30',
                'deleted_at' => NULL,
                'discount' => 5.0,
                'id' => 88,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 31.56,
                'txn_id' => '#118',
                'updated_at' => '2023-09-30 06:25:44',
            ),
            76 => 
            array (
                'booking_id' => 119,
                'created_at' => '2023-09-30 06:37:15',
                'customer_id' => 3,
                'datetime' => '2023-09-30 12:07:14',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 89,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 23.95,
                'txn_id' => '#119',
                'updated_at' => '2023-09-30 06:37:15',
            ),
            77 => 
            array (
                'booking_id' => 120,
                'created_at' => '2023-09-30 06:40:21',
                'customer_id' => 3,
                'datetime' => '2023-09-30 12:10:19',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 90,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 29.0,
                'txn_id' => '#120',
                'updated_at' => '2023-09-30 06:40:34',
            ),
            78 => 
            array (
                'booking_id' => 121,
                'created_at' => '2023-09-30 06:55:52',
                'customer_id' => 3,
                'datetime' => '2023-09-30 12:25:49',
                'deleted_at' => NULL,
                'discount' => NULL,
                'id' => 91,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 14.29,
                'txn_id' => '#121',
                'updated_at' => '2023-09-30 06:56:01',
            ),
            79 => 
            array (
                'booking_id' => 122,
                'created_at' => '2023-09-30 07:03:21',
                'customer_id' => 3,
                'datetime' => '2023-09-30 12:33:19',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 92,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 19.12,
                'txn_id' => '#122',
                'updated_at' => '2023-09-30 07:03:21',
            ),
            80 => 
            array (
                'booking_id' => 123,
                'created_at' => '2023-09-30 07:12:47',
                'customer_id' => 3,
                'datetime' => '2023-09-30 12:42:46',
                'deleted_at' => NULL,
                'discount' => 1.0,
                'id' => 93,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 19.54,
                'txn_id' => '#123',
                'updated_at' => '2023-09-30 07:13:22',
            ),
            81 => 
            array (
                'booking_id' => 124,
                'created_at' => '2023-09-30 07:15:42',
                'customer_id' => 3,
                'datetime' => '2023-09-30 12:45:40',
                'deleted_at' => NULL,
                'discount' => 10.0,
                'id' => 94,
                'other_transaction_detail' => NULL,
                'payment_status' => 'advanced_paid',
                'payment_type' => 'stripe',
                'total_amount' => 4.232,
                'txn_id' => 'pi_1NvxOdFTMa5P8ht0t6bhQL6o',
                'updated_at' => '2023-09-30 07:15:42',
            ),
            82 => 
            array (
                'booking_id' => 124,
                'created_at' => '2023-09-30 07:21:17',
                'customer_id' => 3,
                'datetime' => '2023-09-30 12:51:15',
                'deleted_at' => NULL,
                'discount' => 10.0,
                'id' => 95,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 60.148,
                'txn_id' => 'pi_1NvxTzFTMa5P8ht0Hyh21Nyp',
                'updated_at' => '2023-09-30 07:21:17',
            ),
            83 => 
            array (
                'booking_id' => 126,
                'created_at' => '2023-09-30 07:29:33',
                'customer_id' => 3,
                'datetime' => '2023-09-30 12:59:32',
                'deleted_at' => NULL,
                'discount' => 3.0,
                'id' => 97,
                'other_transaction_detail' => NULL,
                'payment_status' => 'advanced_paid',
                'payment_type' => 'stripe',
                'total_amount' => 3.965,
                'txn_id' => 'pi_1Nvxc1FTMa5P8ht0L6zswKYq',
                'updated_at' => '2023-09-30 07:29:33',
            ),
            84 => 
            array (
                'booking_id' => 126,
                'created_at' => '2023-09-30 07:32:29',
                'customer_id' => 3,
                'datetime' => '2023-09-30 13:02:28',
                'deleted_at' => NULL,
                'discount' => 3.0,
                'id' => 98,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 35.685,
                'txn_id' => '#126',
                'updated_at' => '2023-09-30 07:32:29',
            ),
            85 => 
            array (
                'booking_id' => 127,
                'created_at' => '2023-09-30 07:45:30',
                'customer_id' => 3,
                'datetime' => '2023-09-30 13:15:29',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 99,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 41.8,
                'txn_id' => '#127',
                'updated_at' => '2023-09-30 07:45:30',
            ),
            86 => 
            array (
                'booking_id' => 128,
                'created_at' => '2023-09-30 10:22:09',
                'customer_id' => 3,
                'datetime' => '2023-09-30 15:52:08',
                'deleted_at' => NULL,
                'discount' => 1.0,
                'id' => 100,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 12.27,
                'txn_id' => '#128',
                'updated_at' => '2023-09-30 10:22:09',
            ),
            87 => 
            array (
                'booking_id' => 129,
                'created_at' => '2023-09-30 10:33:08',
                'customer_id' => 3,
                'datetime' => '2023-09-30 16:03:07',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 101,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 29.73,
                'txn_id' => '#129',
                'updated_at' => '2023-09-30 10:33:22',
            ),
            88 => 
            array (
                'booking_id' => 131,
                'created_at' => '2023-09-30 10:40:44',
                'customer_id' => 3,
                'datetime' => '2023-09-30 16:10:42',
                'deleted_at' => NULL,
                'discount' => NULL,
                'id' => 102,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 46.19,
                'txn_id' => '#131',
                'updated_at' => '2023-09-30 10:40:54',
            ),
            89 => 
            array (
                'booking_id' => 134,
                'created_at' => '2023-09-30 13:43:15',
                'customer_id' => 3,
                'datetime' => '2023-09-30 19:13:13',
                'deleted_at' => NULL,
                'discount' => NULL,
                'id' => 103,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 39.9,
                'txn_id' => '#134',
                'updated_at' => '2023-09-30 13:44:09',
            ),
            90 => 
            array (
                'booking_id' => 133,
                'created_at' => '2023-09-30 13:50:08',
                'customer_id' => 3,
                'datetime' => '2023-09-30 19:20:07',
                'deleted_at' => NULL,
                'discount' => NULL,
                'id' => 104,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 33.4,
                'txn_id' => '#133',
                'updated_at' => '2023-09-30 13:50:08',
            ),
            91 => 
            array (
                'booking_id' => 135,
                'created_at' => '2023-09-30 13:54:25',
                'customer_id' => 3,
                'datetime' => '2023-09-30 19:24:23',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 105,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 16.6,
                'txn_id' => '#135',
                'updated_at' => '2023-09-30 13:54:25',
            ),
            92 => 
            array (
                'booking_id' => 136,
                'created_at' => '2023-10-02 05:30:03',
                'customer_id' => 3,
                'datetime' => '2023-10-02 11:00:01',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 106,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 35.5,
                'txn_id' => '#136',
                'updated_at' => '2023-10-02 05:30:03',
            ),
            93 => 
            array (
                'booking_id' => 137,
                'created_at' => '2023-10-02 05:35:51',
                'customer_id' => 3,
                'datetime' => '2023-10-02 11:05:49',
                'deleted_at' => NULL,
                'discount' => 4.0,
                'id' => 107,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'cash',
                'total_amount' => 40.12,
                'txn_id' => '#137',
                'updated_at' => '2023-10-06 15:41:43',
            ),
            94 => 
            array (
                'booking_id' => 138,
                'created_at' => '2023-10-02 05:48:43',
                'customer_id' => 3,
                'datetime' => '2023-10-02 11:18:41',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 108,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 29.0,
                'txn_id' => '#138',
                'updated_at' => '2023-10-02 05:49:10',
            ),
            95 => 
            array (
                'booking_id' => 139,
                'created_at' => '2023-10-02 05:57:10',
                'customer_id' => 3,
                'datetime' => '2023-10-02 11:27:08',
                'deleted_at' => NULL,
                'discount' => 5.0,
                'id' => 109,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 33.3,
                'txn_id' => '#139',
                'updated_at' => '2023-10-02 05:57:23',
            ),
            96 => 
            array (
                'booking_id' => 140,
                'created_at' => '2023-10-02 06:03:29',
                'customer_id' => 3,
                'datetime' => '2023-10-02 11:33:27',
                'deleted_at' => NULL,
                'discount' => 10.0,
                'id' => 110,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 51.25,
                'txn_id' => '#140',
                'updated_at' => '2023-10-02 06:03:44',
            ),
            97 => 
            array (
                'booking_id' => 141,
                'created_at' => '2023-10-02 06:09:17',
                'customer_id' => 3,
                'datetime' => '2023-10-02 11:39:15',
                'deleted_at' => NULL,
                'discount' => 10.0,
                'id' => 111,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 40.54,
                'txn_id' => '#141',
                'updated_at' => '2023-10-02 06:09:29',
            ),
            98 => 
            array (
                'booking_id' => 142,
                'created_at' => '2023-10-02 06:14:32',
                'customer_id' => 3,
                'datetime' => '2023-10-02 11:44:31',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 112,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 13.45,
                'txn_id' => '#142',
                'updated_at' => '2023-10-02 06:14:32',
            ),
            99 => 
            array (
                'booking_id' => 143,
                'created_at' => '2023-10-02 06:22:00',
                'customer_id' => 3,
                'datetime' => '2023-10-02 11:51:58',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 113,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 43.9,
                'txn_id' => '#143',
                'updated_at' => '2023-10-02 06:22:00',
            ),
            100 => 
            array (
                'booking_id' => 144,
                'created_at' => '2023-10-02 07:11:05',
                'customer_id' => 3,
                'datetime' => '2023-10-02 12:41:03',
                'deleted_at' => NULL,
                'discount' => NULL,
                'id' => 114,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 40.75,
                'txn_id' => '#144',
                'updated_at' => '2023-10-02 07:11:05',
            ),
            101 => 
            array (
                'booking_id' => 145,
                'created_at' => '2023-10-02 07:29:20',
                'customer_id' => 3,
                'datetime' => '2023-10-02 12:59:18',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 115,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 29.46,
                'txn_id' => '#145',
                'updated_at' => '2023-10-02 07:29:20',
            ),
            102 => 
            array (
                'booking_id' => 146,
                'created_at' => '2023-10-02 07:35:09',
                'customer_id' => 3,
                'datetime' => '2023-10-02 13:05:08',
                'deleted_at' => NULL,
                'discount' => 4.0,
                'id' => 116,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 23.87,
                'txn_id' => '#146',
                'updated_at' => '2023-10-02 07:35:30',
            ),
            103 => 
            array (
                'booking_id' => 147,
                'created_at' => '2023-10-02 07:44:25',
                'customer_id' => 3,
                'datetime' => '2023-10-02 13:14:23',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 117,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 42.07,
                'txn_id' => 'pi_1NwgnTFTMa5P8ht0LmkjkURx',
                'updated_at' => '2023-10-02 07:44:25',
            ),
            104 => 
            array (
                'booking_id' => 148,
                'created_at' => '2023-10-02 09:34:39',
                'customer_id' => 3,
                'datetime' => '2023-10-02 15:04:37',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 118,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 40.67,
                'txn_id' => '#148',
                'updated_at' => '2023-10-02 09:35:15',
            ),
            105 => 
            array (
                'booking_id' => 149,
                'created_at' => '2023-10-02 09:44:04',
                'customer_id' => 3,
                'datetime' => '2023-10-02 15:14:02',
                'deleted_at' => NULL,
                'discount' => 1.0,
                'id' => 119,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 37.26,
                'txn_id' => '#149',
                'updated_at' => '2023-10-02 09:44:04',
            ),
            106 => 
            array (
                'booking_id' => 150,
                'created_at' => '2023-10-02 09:53:18',
                'customer_id' => 3,
                'datetime' => '2023-10-02 15:23:17',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 120,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 22.33,
                'txn_id' => '#150',
                'updated_at' => '2023-10-02 09:53:18',
            ),
            107 => 
            array (
                'booking_id' => 151,
                'created_at' => '2023-10-02 10:00:23',
                'customer_id' => 3,
                'datetime' => '2023-10-02 15:30:21',
                'deleted_at' => NULL,
                'discount' => NULL,
                'id' => 121,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 32.81,
                'txn_id' => 'pi_1Nwiv4FTMa5P8ht0J5VSoZAF',
                'updated_at' => '2023-10-02 10:00:23',
            ),
            108 => 
            array (
                'booking_id' => 152,
                'created_at' => '2023-10-02 10:07:23',
                'customer_id' => 3,
                'datetime' => '2023-10-02 15:37:21',
                'deleted_at' => NULL,
                'discount' => NULL,
                'id' => 122,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 20.8,
                'txn_id' => '#152',
                'updated_at' => '2023-10-02 10:07:23',
            ),
            109 => 
            array (
                'booking_id' => 153,
                'created_at' => '2023-10-02 10:18:50',
                'customer_id' => 3,
                'datetime' => '2023-10-02 15:48:48',
                'deleted_at' => NULL,
                'discount' => NULL,
                'id' => 123,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 46.0,
                'txn_id' => '#153',
                'updated_at' => '2023-10-02 10:18:50',
            ),
            110 => 
            array (
                'booking_id' => 154,
                'created_at' => '2023-10-02 10:25:49',
                'customer_id' => 3,
                'datetime' => '2023-10-02 15:55:47',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 124,
                'other_transaction_detail' => NULL,
                'payment_status' => 'advanced_paid',
                'payment_type' => 'stripe',
                'total_amount' => 2.367,
                'txn_id' => 'pi_1NwjJhFTMa5P8ht0WSSxaGif',
                'updated_at' => '2023-10-02 10:25:49',
            ),
            111 => 
            array (
                'booking_id' => 154,
                'created_at' => '2023-10-02 10:29:32',
                'customer_id' => 3,
                'datetime' => '2023-10-02 15:59:30',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 125,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 21.303,
                'txn_id' => '#154',
                'updated_at' => '2023-10-02 10:29:32',
            ),
            112 => 
            array (
                'booking_id' => 155,
                'created_at' => '2023-10-02 10:33:53',
                'customer_id' => 3,
                'datetime' => '2023-10-02 16:03:51',
                'deleted_at' => NULL,
                'discount' => 5.0,
                'id' => 126,
                'other_transaction_detail' => NULL,
                'payment_status' => 'advanced_paid',
                'payment_type' => 'wallet',
                'total_amount' => 2.1068,
                'txn_id' => '#155',
                'updated_at' => '2023-10-02 10:33:53',
            ),
            113 => 
            array (
                'booking_id' => 155,
                'created_at' => '2023-10-02 10:46:52',
                'customer_id' => 3,
                'datetime' => '2023-10-02 16:16:50',
                'deleted_at' => NULL,
                'discount' => 5.0,
                'id' => 127,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 50.5632,
                'txn_id' => '#155',
                'updated_at' => '2023-10-02 10:46:52',
            ),
            114 => 
            array (
                'booking_id' => 156,
                'created_at' => '2023-10-02 11:39:23',
                'customer_id' => 3,
                'datetime' => '2023-10-02 17:09:22',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 128,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 28.4,
                'txn_id' => '#156',
                'updated_at' => '2023-10-02 11:39:23',
            ),
            115 => 
            array (
                'booking_id' => 157,
                'created_at' => '2023-10-02 11:45:51',
                'customer_id' => 3,
                'datetime' => '2023-10-02 17:15:49',
                'deleted_at' => NULL,
                'discount' => 1.0,
                'id' => 129,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 10.88,
                'txn_id' => '#157',
                'updated_at' => '2023-10-02 11:46:05',
            ),
            116 => 
            array (
                'booking_id' => 158,
                'created_at' => '2023-10-02 11:54:37',
                'customer_id' => 3,
                'datetime' => '2023-10-02 17:24:35',
                'deleted_at' => NULL,
                'discount' => 4.0,
                'id' => 130,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 29.66,
                'txn_id' => '#158',
                'updated_at' => '2023-10-02 11:54:37',
            ),
            117 => 
            array (
                'booking_id' => 159,
                'created_at' => '2023-10-02 12:03:03',
                'customer_id' => 3,
                'datetime' => '2023-10-02 17:33:02',
                'deleted_at' => NULL,
                'discount' => NULL,
                'id' => 131,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 33.6,
                'txn_id' => 'pi_1NwkplFTMa5P8ht0sL9MxDRE',
                'updated_at' => '2023-10-02 12:03:03',
            ),
            118 => 
            array (
                'booking_id' => 160,
                'created_at' => '2023-10-02 12:11:24',
                'customer_id' => 3,
                'datetime' => '2023-10-02 17:41:22',
                'deleted_at' => NULL,
                'discount' => NULL,
                'id' => 132,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 30.75,
                'txn_id' => 'pi_1NwkxnFTMa5P8ht0d9Nh20KT',
                'updated_at' => '2023-10-02 12:11:24',
            ),
            119 => 
            array (
                'booking_id' => 161,
                'created_at' => '2023-10-02 12:15:44',
                'customer_id' => 3,
                'datetime' => '2023-10-02 17:45:43',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 133,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 35.5,
                'txn_id' => '#161',
                'updated_at' => '2023-10-02 12:15:44',
            ),
            120 => 
            array (
                'booking_id' => 162,
                'created_at' => '2023-10-02 12:23:44',
                'customer_id' => 3,
                'datetime' => '2023-10-02 17:53:43',
                'deleted_at' => NULL,
                'discount' => 4.0,
                'id' => 134,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 19.83,
                'txn_id' => '#162',
                'updated_at' => '2023-10-02 12:23:55',
            ),
            121 => 
            array (
                'booking_id' => 165,
                'created_at' => '2023-10-02 12:39:08',
                'customer_id' => 3,
                'datetime' => '2023-10-02 18:09:07',
                'deleted_at' => NULL,
                'discount' => 4.0,
                'id' => 135,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 21.85,
                'txn_id' => '#165',
                'updated_at' => '2023-10-02 12:39:17',
            ),
            122 => 
            array (
                'booking_id' => 166,
                'created_at' => '2023-10-02 12:44:45',
                'customer_id' => 3,
                'datetime' => '2023-10-02 18:14:44',
                'deleted_at' => NULL,
                'discount' => 5.0,
                'id' => 136,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 37.81,
                'txn_id' => '#166',
                'updated_at' => '2023-10-02 12:44:45',
            ),
            123 => 
            array (
                'booking_id' => 167,
                'created_at' => '2023-10-02 12:48:45',
                'customer_id' => 3,
                'datetime' => '2023-10-02 18:18:43',
                'deleted_at' => NULL,
                'discount' => 4.0,
                'id' => 137,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 63.33,
                'txn_id' => '#167',
                'updated_at' => '2023-10-02 12:48:45',
            ),
            124 => 
            array (
                'booking_id' => 168,
                'created_at' => '2023-10-02 12:58:42',
                'customer_id' => 3,
                'datetime' => '2023-10-02 18:28:41',
                'deleted_at' => NULL,
                'discount' => 4.0,
                'id' => 138,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 42.14,
                'txn_id' => '#168',
                'updated_at' => '2023-10-02 12:58:54',
            ),
            125 => 
            array (
                'booking_id' => 169,
                'created_at' => '2023-10-02 13:05:36',
                'customer_id' => 3,
                'datetime' => '2023-10-02 18:35:35',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 139,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 34.65,
                'txn_id' => '#169',
                'updated_at' => '2023-10-02 13:05:36',
            ),
            126 => 
            array (
                'booking_id' => 170,
                'created_at' => '2023-10-02 13:11:59',
                'customer_id' => 3,
                'datetime' => '2023-10-02 18:41:57',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 140,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 30.25,
                'txn_id' => '#170',
                'updated_at' => '2023-10-02 13:11:59',
            ),
            127 => 
            array (
                'booking_id' => 171,
                'created_at' => '2023-10-02 13:17:48',
                'customer_id' => 3,
                'datetime' => '2023-10-02 18:47:47',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 141,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 55.71,
                'txn_id' => '#171',
                'updated_at' => '2023-10-02 13:17:54',
            ),
            128 => 
            array (
                'booking_id' => 172,
                'created_at' => '2023-10-02 13:24:05',
                'customer_id' => 3,
                'datetime' => '2023-10-02 18:54:04',
                'deleted_at' => NULL,
                'discount' => NULL,
                'id' => 142,
                'other_transaction_detail' => NULL,
                'payment_status' => 'advanced_paid',
                'payment_type' => 'wallet',
                'total_amount' => 1.3835,
                'txn_id' => '#172',
                'updated_at' => '2023-10-02 13:24:05',
            ),
            129 => 
            array (
                'booking_id' => 172,
                'created_at' => '2023-10-02 13:26:57',
                'customer_id' => 3,
                'datetime' => '2023-10-02 18:56:56',
                'deleted_at' => NULL,
                'discount' => NULL,
                'id' => 143,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 26.2865,
                'txn_id' => '#172',
                'updated_at' => '2023-10-02 13:26:57',
            ),
            130 => 
            array (
                'booking_id' => 173,
                'created_at' => '2023-10-02 13:32:17',
                'customer_id' => 3,
                'datetime' => '2023-10-02 19:02:15',
                'deleted_at' => NULL,
                'discount' => 5.0,
                'id' => 144,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 63.17,
                'txn_id' => '#173',
                'updated_at' => '2023-10-02 13:32:28',
            ),
            131 => 
            array (
                'booking_id' => 178,
                'created_at' => '2023-10-03 12:16:33',
                'customer_id' => 50,
                'datetime' => '2023-10-03 17:46:31',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 145,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 51.25,
                'txn_id' => '#178',
                'updated_at' => '2023-10-03 12:16:33',
            ),
            132 => 
            array (
                'booking_id' => 179,
                'created_at' => '2023-10-03 12:24:44',
                'customer_id' => 50,
                'datetime' => '2023-10-03 17:54:42',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 146,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending',
                'payment_type' => 'cash',
                'total_amount' => 16.6,
                'txn_id' => '#179',
                'updated_at' => '2023-10-03 12:24:44',
            ),
            133 => 
            array (
                'booking_id' => 180,
                'created_at' => '2023-10-03 12:35:12',
                'customer_id' => 49,
                'datetime' => '2023-10-03 18:05:10',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 147,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 42.85,
                'txn_id' => '#180',
                'updated_at' => '2023-10-03 12:35:29',
            ),
            134 => 
            array (
                'booking_id' => 181,
                'created_at' => '2023-10-03 12:40:33',
                'customer_id' => 48,
                'datetime' => '2023-10-03 18:10:31',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 148,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 16.6,
                'txn_id' => '#181',
                'updated_at' => '2023-10-03 12:40:33',
            ),
            135 => 
            array (
                'booking_id' => 182,
                'created_at' => '2023-10-03 13:04:34',
                'customer_id' => 48,
                'datetime' => '2023-10-03 18:34:33',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 149,
                'other_transaction_detail' => NULL,
                'payment_status' => 'advanced_paid',
                'payment_type' => 'wallet',
                'total_amount' => 0.689,
                'txn_id' => '#182',
                'updated_at' => '2023-10-03 13:04:34',
            ),
            136 => 
            array (
                'booking_id' => 182,
                'created_at' => '2023-10-03 13:07:26',
                'customer_id' => 48,
                'datetime' => '2023-10-03 18:37:24',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 150,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 44.261,
                'txn_id' => 'pi_1Nx8JdFTMa5P8ht0koAX6sQp',
                'updated_at' => '2023-10-03 13:07:26',
            ),
            137 => 
            array (
                'booking_id' => 183,
                'created_at' => '2023-10-03 13:11:34',
                'customer_id' => 47,
                'datetime' => '2023-10-03 18:41:32',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 151,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending',
                'payment_type' => 'cash',
                'total_amount' => 48.1,
                'txn_id' => '#183',
                'updated_at' => '2023-10-03 13:11:34',
            ),
            138 => 
            array (
                'booking_id' => 184,
                'created_at' => '2023-10-03 13:13:54',
                'customer_id' => 46,
                'datetime' => '2023-10-03 18:43:52',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 152,
                'other_transaction_detail' => NULL,
                'payment_status' => 'advanced_paid',
                'payment_type' => 'wallet',
                'total_amount' => 0.689,
                'txn_id' => '#184',
                'updated_at' => '2023-10-03 13:13:54',
            ),
            139 => 
            array (
                'booking_id' => 184,
                'created_at' => '2023-10-03 13:16:28',
                'customer_id' => 46,
                'datetime' => '2023-10-03 18:46:27',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 153,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 33.761,
                'txn_id' => '#184',
                'updated_at' => '2023-10-03 13:16:28',
            ),
            140 => 
            array (
                'booking_id' => 186,
                'created_at' => '2023-10-05 06:01:38',
                'customer_id' => 41,
                'datetime' => '2023-10-05 11:31:36',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 154,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 16.6,
                'txn_id' => '#186',
                'updated_at' => '2023-10-05 06:01:48',
            ),
            141 => 
            array (
                'booking_id' => 187,
                'created_at' => '2023-10-05 06:09:07',
                'customer_id' => 40,
                'datetime' => '2023-10-05 11:39:05',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 155,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 39.7,
                'txn_id' => '#187',
                'updated_at' => '2023-10-05 06:09:07',
            ),
            142 => 
            array (
                'booking_id' => 188,
                'created_at' => '2023-10-05 06:14:54',
                'customer_id' => 39,
                'datetime' => '2023-10-05 11:44:52',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 156,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 48.1,
                'txn_id' => '#188',
                'updated_at' => '2023-10-05 06:14:54',
            ),
            143 => 
            array (
                'booking_id' => 189,
                'created_at' => '2023-10-05 06:19:17',
                'customer_id' => 39,
                'datetime' => '2023-10-05 11:49:14',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 157,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 16.6,
                'txn_id' => 'pi_1NxktiFTMa5P8ht0YBmufzHJ',
                'updated_at' => '2023-10-05 06:19:17',
            ),
            144 => 
            array (
                'booking_id' => 191,
                'created_at' => '2023-10-05 06:35:50',
                'customer_id' => 38,
                'datetime' => '2023-10-05 12:05:47',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 158,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 51.25,
                'txn_id' => '#191',
                'updated_at' => '2023-10-05 06:35:50',
            ),
            145 => 
            array (
                'booking_id' => 190,
                'created_at' => '2023-10-05 06:36:59',
                'customer_id' => 38,
                'datetime' => '2023-10-05 12:06:57',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 159,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 16.6,
                'txn_id' => '#190',
                'updated_at' => '2023-10-05 06:36:59',
            ),
            146 => 
            array (
                'booking_id' => 193,
                'created_at' => '2023-10-05 06:44:57',
                'customer_id' => 37,
                'datetime' => '2023-10-05 12:14:55',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 160,
                'other_transaction_detail' => NULL,
                'payment_status' => 'advanced_paid',
                'payment_type' => 'wallet',
                'total_amount' => 0.689,
                'txn_id' => '#193',
                'updated_at' => '2023-10-05 06:44:57',
            ),
            147 => 
            array (
                'booking_id' => 193,
                'created_at' => '2023-10-05 06:50:32',
                'customer_id' => 37,
                'datetime' => '2023-10-05 12:20:29',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 161,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 33.761,
                'txn_id' => '#193',
                'updated_at' => '2023-10-05 06:50:32',
            ),
            148 => 
            array (
                'booking_id' => 194,
                'created_at' => '2023-10-05 07:10:21',
                'customer_id' => 48,
                'datetime' => '2023-10-05 12:40:19',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 162,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 41.8,
                'txn_id' => 'pi_1Nxlh7FTMa5P8ht0fURJbVv8',
                'updated_at' => '2023-10-05 07:10:21',
            ),
            149 => 
            array (
                'booking_id' => 195,
                'created_at' => '2023-10-05 07:19:19',
                'customer_id' => 3,
                'datetime' => '2023-10-05 12:49:17',
                'deleted_at' => NULL,
                'discount' => NULL,
                'id' => 163,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 46.19,
                'txn_id' => '#195',
                'updated_at' => '2023-10-05 07:19:19',
            ),
            150 => 
            array (
                'booking_id' => 197,
                'created_at' => '2023-10-05 07:29:23',
                'customer_id' => 50,
                'datetime' => '2023-10-05 12:59:21',
                'deleted_at' => NULL,
                'discount' => 4.0,
                'id' => 164,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 41.51,
                'txn_id' => 'pi_1NxlzRFTMa5P8ht0vLCtEhGq',
                'updated_at' => '2023-10-05 07:29:23',
            ),
            151 => 
            array (
                'booking_id' => 199,
                'created_at' => '2023-10-05 07:35:54',
                'customer_id' => 49,
                'datetime' => '2023-10-05 13:05:52',
                'deleted_at' => NULL,
                'discount' => 2.0,
                'id' => 165,
                'other_transaction_detail' => NULL,
                'payment_status' => 'pending_by_admin',
                'payment_type' => 'cash',
                'total_amount' => 24.47,
                'txn_id' => '#199',
                'updated_at' => '2023-10-05 07:39:08',
            ),
            152 => 
            array (
                'booking_id' => 201,
                'created_at' => '2023-10-05 08:12:09',
                'customer_id' => 47,
                'datetime' => '2023-10-05 13:42:07',
                'deleted_at' => NULL,
                'discount' => 4.0,
                'id' => 166,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 36.13,
                'txn_id' => '#201',
                'updated_at' => '2023-10-05 08:12:09',
            ),
            153 => 
            array (
                'booking_id' => 202,
                'created_at' => '2023-10-05 08:18:49',
                'customer_id' => 43,
                'datetime' => '2023-10-05 13:48:47',
                'deleted_at' => NULL,
                'discount' => 4.0,
                'id' => 167,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 38.1,
                'txn_id' => '#202',
                'updated_at' => '2023-10-05 08:18:49',
            ),
            154 => 
            array (
                'booking_id' => 203,
                'created_at' => '2023-10-05 09:20:38',
                'customer_id' => 46,
                'datetime' => '2023-10-05 14:50:36',
                'deleted_at' => NULL,
                'discount' => 7.0,
                'id' => 168,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 30.75,
                'txn_id' => '#203',
                'updated_at' => '2023-10-05 09:20:38',
            ),
            155 => 
            array (
                'booking_id' => 207,
                'created_at' => '2023-10-05 10:07:14',
                'customer_id' => 44,
                'datetime' => '2023-10-05 15:37:11',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 169,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 38.99,
                'txn_id' => '#207',
                'updated_at' => '2023-10-05 10:07:14',
            ),
            156 => 
            array (
                'booking_id' => 208,
                'created_at' => '2023-10-05 10:12:15',
                'customer_id' => 45,
                'datetime' => '2023-10-05 15:42:13',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 170,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 16.6,
                'txn_id' => '#208',
                'updated_at' => '2023-10-05 10:12:15',
            ),
            157 => 
            array (
                'booking_id' => 209,
                'created_at' => '2023-10-05 10:16:08',
                'customer_id' => 42,
                'datetime' => '2023-10-05 15:46:05',
                'deleted_at' => NULL,
                'discount' => 0.0,
                'id' => 171,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'wallet',
                'total_amount' => 37.6,
                'txn_id' => '#209',
                'updated_at' => '2023-10-05 10:16:08',
            ),
            158 => 
            array (
                'booking_id' => 221,
                'created_at' => '2023-10-06 09:59:15',
                'customer_id' => 3,
                'datetime' => '2023-10-06 15:29:13',
                'deleted_at' => NULL,
                'discount' => 7.0,
                'id' => 172,
                'other_transaction_detail' => NULL,
                'payment_status' => 'paid',
                'payment_type' => 'stripe',
                'total_amount' => 43.9,
                'txn_id' => 'pi_1NyAo8FTMa5P8ht09CGuoAHO',
                'updated_at' => '2023-10-06 09:59:15',
            ),
        ));
        
        
    }
}